<?php
namespace aliyun\sdk\services\Ecs\request;

use aliyun\sdk\services\Ecs\EcsCommon;

/**
 * @method $this setSourceRegionId($SourceRegionId)
 * @method string getSourceRegionId()
 * @method $this setRegionId($RegionId)
 * @method string getRegionId()
 * @method $this setTemplateTag($TemplateTag)
 * @method array getTemplateTag()
 * @method $this setLaunchTemplateName($LaunchTemplateName)
 * @method string getLaunchTemplateName()
 * @method $this setVersionDescription($VersionDescription)
 * @method string getVersionDescription()
 * @method $this setImageId($ImageId)
 * @method string getImageId()
 * @method $this setImageOwnerAlias($ImageOwnerAlias)
 * @method string getImageOwnerAlias()
 * @method $this setPasswordInherit($PasswordInherit)
 * @method boolean getPasswordInherit()
 * @method $this setInstanceType($InstanceType)
 * @method string getInstanceType()
 * @method $this setSecurityGroupId($SecurityGroupId)
 * @method string getSecurityGroupId()
 * @method $this setVpcId($VpcId)
 * @method string getVpcId()
 * @method $this setVSwitchId($VSwitchId)
 * @method string getVSwitchId()
 * @method $this setInstanceName($InstanceName)
 * @method string getInstanceName()
 * @method $this setDescription($Description)
 * @method string getDescription()
 * @method $this setInternetMaxBandwidthIn($InternetMaxBandwidthIn)
 * @method integer getInternetMaxBandwidthIn()
 * @method $this setInternetMaxBandwidthOut($InternetMaxBandwidthOut)
 * @method integer getInternetMaxBandwidthOut()
 * @method $this setHostName($HostName)
 * @method string getHostName()
 * @method $this setZoneId($ZoneId)
 * @method string getZoneId()
 * @method $this setSystemDisk_Category($SystemDisk_Category)
 * @method string getSystemDisk_Category()
 * @method $this setSystemDisk_Size($SystemDisk_Size)
 * @method integer getSystemDisk_Size()
 * @method $this setSystemDisk_DiskName($SystemDisk_DiskName)
 * @method string getSystemDisk_DiskName()
 * @method $this setSystemDisk_Description($SystemDisk_Description)
 * @method string getSystemDisk_Description()
 * @method $this setSystemDisk_Iops($SystemDisk_Iops)
 * @method integer getSystemDisk_Iops()
 * @method $this setDataDisk($DataDisk)
 * @method array getDataDisk()
 * @method $this setIoOptimized($IoOptimized)
 * @method string getIoOptimized()
 * @method $this setNetworkInterface($NetworkInterface)
 * @method array getNetworkInterface()
 * @method $this setInstanceChargeType($InstanceChargeType)
 * @method string getInstanceChargeType()
 * @method $this setPeriod($Period)
 * @method integer getPeriod()
 * @method $this setInternetChargeType($InternetChargeType)
 * @method string getInternetChargeType()
 * @method $this setEnableVmOsConfig($EnableVmOsConfig)
 * @method boolean getEnableVmOsConfig()
 * @method $this setNetworkType($NetworkType)
 * @method string getNetworkType()
 * @method $this setUserData($UserData)
 * @method string getUserData()
 * @method $this setKeyPairName($KeyPairName)
 * @method string getKeyPairName()
 * @method $this setRamRoleName($RamRoleName)
 * @method string getRamRoleName()
 * @method $this setAutoReleaseTime($AutoReleaseTime)
 * @method string getAutoReleaseTime()
 * @method $this setSpotStrategy($SpotStrategy)
 * @method string getSpotStrategy()
 * @method $this setSpotPriceLimit($SpotPriceLimit)
 * @method float getSpotPriceLimit()
 * @method $this setSpotDuration($SpotDuration)
 * @method integer getSpotDuration()
 * @method $this setResourceGroupId($ResourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setTemplateResourceGroupId($TemplateResourceGroupId)
 * @method string getTemplateResourceGroupId()
 * @method $this setSecurityEnhancementStrategy($SecurityEnhancementStrategy)
 * @method string getSecurityEnhancementStrategy()
 * @method $this setTag($Tag)
 * @method array getTag()
 */
final class CreateLaunchTemplate extends EcsCommon
{
    public $action = 'CreateLaunchTemplate';
}
