<?php
namespace aliyun\sdk\services\Ecs\request;

use aliyun\sdk\services\Ecs\EcsCommon;

/**
 * @method $this setSourceRegionId($SourceRegionId)
 * @method string getSourceRegionId()
 * @method $this setRegionId($RegionId)
 * @method string getRegionId()
 * @method $this setVpcId($VpcId)
 * @method string getVpcId()
 * @method $this setVSwitchId($VSwitchId)
 * @method string getVSwitchId()
 * @method $this setZoneId($ZoneId)
 * @method string getZoneId()
 * @method $this setInstanceNetworkType($InstanceNetworkType)
 * @method string getInstanceNetworkType()
 * @method $this setSecurityGroupId($SecurityGroupId)
 * @method string getSecurityGroupId()
 * @method $this setInstanceIds($InstanceIds)
 * @method string getInstanceIds()
 * @method $this setPageNumber($PageNumber)
 * @method integer getPageNumber()
 * @method $this setPageSize($PageSize)
 * @method integer getPageSize()
 * @method $this setInnerIpAddresses($InnerIpAddresses)
 * @method string getInnerIpAddresses()
 * @method $this setPrivateIpAddresses($PrivateIpAddresses)
 * @method string getPrivateIpAddresses()
 * @method $this setPublicIpAddresses($PublicIpAddresses)
 * @method string getPublicIpAddresses()
 * @method $this setEipAddresses($EipAddresses)
 * @method string getEipAddresses()
 * @method $this setInstanceChargeType($InstanceChargeType)
 * @method string getInstanceChargeType()
 * @method $this setInternetChargeType($InternetChargeType)
 * @method string getInternetChargeType()
 * @method $this setInstanceName($InstanceName)
 * @method string getInstanceName()
 * @method $this setImageId($ImageId)
 * @method string getImageId()
 * @method $this setStatus($Status)
 * @method string getStatus()
 * @method $this setLockReason($LockReason)
 * @method string getLockReason()
 * @method $this setFilter_1_Key($Filter_1_Key)
 * @method string getFilter_1_Key()
 * @method $this setFilter_2_Key($Filter_2_Key)
 * @method string getFilter_2_Key()
 * @method $this setFilter_3_Key($Filter_3_Key)
 * @method string getFilter_3_Key()
 * @method $this setFilter_4_Key($Filter_4_Key)
 * @method string getFilter_4_Key()
 * @method $this setFilter_1_Value($Filter_1_Value)
 * @method string getFilter_1_Value()
 * @method $this setFilter_2_Value($Filter_2_Value)
 * @method string getFilter_2_Value()
 * @method $this setFilter_3_Value($Filter_3_Value)
 * @method string getFilter_3_Value()
 * @method $this setFilter_4_Value($Filter_4_Value)
 * @method string getFilter_4_Value()
 * @method $this setDeviceAvailable($DeviceAvailable)
 * @method boolean getDeviceAvailable()
 * @method $this setIoOptimized($IoOptimized)
 * @method boolean getIoOptimized()
 * @method $this setNeedSaleCycle($NeedSaleCycle)
 * @method boolean getNeedSaleCycle()
 * @method $this setTag($Tag)
 * @method array getTag()
 * @method $this setInstanceType($InstanceType)
 * @method string getInstanceType()
 * @method $this setInstanceTypeFamily($InstanceTypeFamily)
 * @method string getInstanceTypeFamily()
 * @method $this setKeyPairName($KeyPairName)
 * @method string getKeyPairName()
 * @method $this setResourceGroupId($ResourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setHpcClusterId($HpcClusterId)
 * @method string getHpcClusterId()
 * @method $this setRdmaIpAddresses($RdmaIpAddresses)
 * @method string getRdmaIpAddresses()
 * @method $this setDryRun($DryRun)
 * @method boolean getDryRun()
 */
final class DescribeInstances extends EcsCommon
{
    public $action = 'DescribeInstances';
}
