<?php
namespace aliyun\sdk\services\Jaq\request;

use aliyun\sdk\services\Jaq\JaqCommon;

/**
 * @method $this setCallerName($CallerName)
 * @method string getCallerName()
 * @method $this setIp($Ip)
 * @method string getIp()
 * @method $this setProtocolVersion($ProtocolVersion)
 * @method string getProtocolVersion()
 * @method $this setSource($Source)
 * @method integer getSource()
 * @method $this setPhoneNumber($PhoneNumber)
 * @method string getPhoneNumber()
 * @method $this setEmail($Email)
 * @method string getEmail()
 * @method $this setUserId($UserId)
 * @method string getUserId()
 * @method $this setIdType($IdType)
 * @method integer getIdType()
 * @method $this setCurrentUrl($CurrentUrl)
 * @method string getCurrentUrl()
 * @method $this setAgent($Agent)
 * @method string getAgent()
 * @method $this setCookie($Cookie)
 * @method string getCookie()
 * @method $this setSessionId($SessionId)
 * @method string getSessionId()
 * @method $this setMacAddress($MacAddress)
 * @method string getMacAddress()
 * @method $this setReferer($Referer)
 * @method string getReferer()
 * @method $this setUserName($UserName)
 * @method string getUserName()
 * @method $this setCompanyName($CompanyName)
 * @method string getCompanyName()
 * @method $this setAddress($Address)
 * @method string getAddress()
 * @method $this setIDNumber($IDNumber)
 * @method string getIDNumber()
 * @method $this setBankCardNumber($BankCardNumber)
 * @method string getBankCardNumber()
 * @method $this setRegisterIp($RegisterIp)
 * @method string getRegisterIp()
 * @method $this setRegisterDate($RegisterDate)
 * @method integer getRegisterDate()
 * @method $this setAccountExist($AccountExist)
 * @method integer getAccountExist()
 * @method $this setExtendData($ExtendData)
 * @method string getExtendData()
 * @method $this setJsToken($JsToken)
 * @method string getJsToken()
 * @method $this setSDKToken($SDKToken)
 * @method string getSDKToken()
 * @method $this setPasswordHash($PasswordHash)
 * @method string getPasswordHash()
 * @method $this setLoginType($LoginType)
 * @method integer getLoginType()
 * @method $this setPasswordCorrect($PasswordCorrect)
 * @method integer getPasswordCorrect()
 */
final class LoginPrevention extends JaqCommon
{
    public $action = 'LoginPrevention';
}
