<?php
namespace aliyun\sdk\services\Emr\request;

use aliyun\sdk\services\Emr\EmrCommon;

/**
 * @method $this setAccessKeyId($AccessKeyId)
 * @method string getAccessKeyId()
 * @method $this setRegionId($RegionId)
 * @method string getRegionId()
 * @method $this setZoneId($ZoneId)
 * @method string getZoneId()
 * @method $this setClusterId($ClusterId)
 * @method string getClusterId()
 * @method $this setName($Name)
 * @method string getName()
 * @method $this setLogPath($LogPath)
 * @method string getLogPath()
 * @method $this setSecurityGroupId($SecurityGroupId)
 * @method string getSecurityGroupId()
 * @method $this setChargeType($ChargeType)
 * @method string getChargeType()
 * @method $this setPeriod($Period)
 * @method integer getPeriod()
 * @method $this setVpcId($VpcId)
 * @method string getVpcId()
 * @method $this setVSwitchId($VSwitchId)
 * @method string getVSwitchId()
 * @method $this setNetType($NetType)
 * @method string getNetType()
 * @method $this setEmrVer($EmrVer)
 * @method string getEmrVer()
 * @method $this setOptionSoftWareList($OptionSoftWareList)
 * @method array getOptionSoftWareList()
 * @method $this setClusterType($ClusterType)
 * @method string getClusterType()
 * @method $this setHighAvailabilityEnable($HighAvailabilityEnable)
 * @method boolean getHighAvailabilityEnable()
 * @method $this setUseLocalMetaDb($UseLocalMetaDb)
 * @method boolean getUseLocalMetaDb()
 * @method $this setIoOptimized($IoOptimized)
 * @method boolean getIoOptimized()
 * @method $this setEasEnable($EasEnable)
 * @method boolean getEasEnable()
 * @method $this setDepositType($DepositType)
 * @method string getDepositType()
 * @method $this setMachineType($MachineType)
 * @method string getMachineType()
 * @method $this setInstanceIdList($InstanceIdList)
 * @method array getInstanceIdList()
 * @method $this setMasterInstanceIdList($MasterInstanceIdList)
 * @method array getMasterInstanceIdList()
 * @method $this setIsResize($IsResize)
 * @method boolean getIsResize()
 * @method $this setOperateType($OperateType)
 * @method string getOperateType()
 */
final class OperateExistsNodeCluster extends EmrCommon
{
    public $action = 'OperateExistsNodeCluster';
}
