<?php

namespace aliyun\sdk\services\Ecs20160314;

use aliyun\sdk\core\lib\Request;

/**
 * Class V20160314
 *
 * @package aliyun\sdk\services\Ecs20160314
 * @method RunInstances_GatedLaunch RunInstances_GatedLaunch()
 * @method ModifyEniQosGroup ModifyEniQosGroup()
 * @method CreateVolumes CreateVolumes()
 * @method DescribeAccountAttributes DescribeAccountAttributes()
 * @method CreateCapacityReservation CreateCapacityReservation()
 * @method AllocateDedicatedHosts AllocateDedicatedHosts()
 * @method DescribeAccountLimits DescribeAccountLimits()
 * @method DeleteEniQosGroup DeleteEniQosGroup()
 * @method RunInstances RunInstances()
 * @method QueryEniQosGroupByEni QueryEniQosGroupByEni()
 * @method ReleaseDedicatedHost ReleaseDedicatedHost()
 * @method CreateOrder CreateOrder()
 * @method DeleteConfigLogSubscriptions DeleteConfigLogSubscriptions()
 * @method CreateConfigLogSubscriptions CreateConfigLogSubscriptions()
 * @method DescribePrice DescribePrice()
 * @method LeaveEniQosGroup LeaveEniQosGroup()
 * @method ModifyInstanceDeployment ModifyInstanceDeployment()
 * @method DescribeKMSKeys DescribeKMSKeys()
 * @method QueryEniQosGroupByInstance QueryEniQosGroupByInstance()
 * @method ModifyReservedInstances ModifyReservedInstances()
 * @method DescribeInstanceNeedReboot DescribeInstanceNeedReboot()
 * @method DescribeResourceRecommendFilters DescribeResourceRecommendFilters()
 * @method DescribeReservedInstances DescribeReservedInstances()
 * @method JoinEniQosGroup JoinEniQosGroup()
 * @method DescribeLinkedKMSKeys DescribeLinkedKMSKeys()
 * @method CreateVolumes_GatedLaunch CreateVolumes_GatedLaunch()
 * @method ReleaseCapacityReservation ReleaseCapacityReservation()
 * @method GetLaunchTemplateData GetLaunchTemplateData()
 * @method DescribeDedicatedHostTypes DescribeDedicatedHostTypes()
 * @method PurchaseReservedInstancesOffering PurchaseReservedInstancesOffering()
 * @method ModifyDedicatedHostAutoRenewAttribute ModifyDedicatedHostAutoRenewAttribute()
 * @method RenewDedicatedHosts RenewDedicatedHosts()
 * @method DescribeConfigLogSubscription DescribeConfigLogSubscription()
 * @method SetInstanceAutoReleaseTime SetInstanceAutoReleaseTime()
 * @method DescribeDedicatedHosts DescribeDedicatedHosts()
 * @method ModifyDedicatedHostAttribute ModifyDedicatedHostAttribute()
 * @method DescribeDedicatedHostAutoRenew DescribeDedicatedHostAutoRenew()
 * @method CreateDisks CreateDisks()
 * @method DescribeReservedInstancePrice DescribeReservedInstancePrice()
 * @method DescribeResourceFilterAttributes DescribeResourceFilterAttributes()
 * @method DescribeResources DescribeResources()
 * @method DescribeBandwidthPrice DescribeBandwidthPrice()
 * @method CreateEniQosGroup CreateEniQosGroup()
 * @method DescribeKMSKeyAttribute DescribeKMSKeyAttribute()
 * @method DescribeCapacityReservations DescribeCapacityReservations()
 * @method DescribeEniQosGroupInfo DescribeEniQosGroupInfo()
 * @method CreateDisks_GatedLaunch CreateDisks_GatedLaunch()
 * @method ModifyDedicatedHostAutoReleaseTime ModifyDedicatedHostAutoReleaseTime()
 */
class V20160314
{
}

/**
 * @method $this setDataDisk($dataDisk)
 * @method array getDataDisk()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setDefaultVpc($defaultVpc)
 * @method string getDefaultVpc()
 * @method $this setNetworkType($networkType)
 * @method string getNetworkType()
 * @method $this setImageId($imageId)
 * @method string getImageId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setClusterId($clusterId)
 * @method string getClusterId()
 * @method $this setInstanceType($instanceType)
 * @method string getInstanceType()
 * @method $this setInternetChargeType($internetChargeType)
 * @method string getInternetChargeType()
 * @method $this setInternetMaxBandwidthOut($internetMaxBandwidthOut)
 * @method int getInternetMaxBandwidthOut()
 * @method $this setInternetMaxBandwidthIn($internetMaxBandwidthIn)
 * @method int getInternetMaxBandwidthIn()
 * @method $this setIoOptimized($ioOptimized)
 * @method string getIoOptimized()
 * @method $this setSystemDisk_Category($systemDisk_Category)
 * @method string getSystemDisk_Category()
 * @method $this setSystemDisk_DiskName($systemDisk_DiskName)
 * @method string getSystemDisk_DiskName()
 * @method $this setSystemDisk_Description($systemDisk_Description)
 * @method string getSystemDisk_Description()
 * @method $this setSystemDisk_Size($systemDisk_Size)
 * @method string getSystemDisk_Size()
 * @method $this setVSwitchId($vSwitchId)
 * @method string getVSwitchId()
 * @method $this setMinAmount($minAmount)
 * @method int getMinAmount()
 * @method $this setMaxAmount($maxAmount)
 * @method int getMaxAmount()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setSecurityGroupId($securityGroupId)
 * @method string getSecurityGroupId()
 * @method $this setInstanceName($instanceName)
 * @method string getInstanceName()
 * @method $this setHostName($hostName)
 * @method string getHostName()
 * @method $this setPassword($password)
 * @method string getPassword()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setAutoReleaseTime($autoReleaseTime)
 * @method string getAutoReleaseTime()
 * @method $this setFromApp($fromApp)
 * @method string getFromApp()
 * @method $this setNodeControllerId($nodeControllerId)
 * @method string getNodeControllerId()
 * @method $this setRelationOrderId($relationOrderId)
 * @method string getRelationOrderId()
 * @method $this setBusinessInfo($businessInfo)
 * @method string getBusinessInfo()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setUserData($userData)
 * @method string getUserData()
 * @method $this setSpotStrategy($spotStrategy)
 * @method string getSpotStrategy()
 */
class RunInstances_GatedLaunch extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setQosGroupName($qosGroupName)
 * @method string getQosGroupName()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setRx($rx)
 * @method int getRx()
 * @method $this setRxPps($rxPps)
 * @method int getRxPps()
 * @method $this setTx($tx)
 * @method int getTx()
 * @method $this setTxPps($txPps)
 * @method int getTxPps()
 */
class ModifyEniQosGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setSnapshotId($snapshotId)
 * @method string getSnapshotId()
 * @method $this setVolumeName($volumeName)
 * @method string getVolumeName()
 * @method $this setSize($size)
 * @method int getSize()
 * @method $this setAmount($amount)
 * @method int getAmount()
 * @method $this setVolumeCategory($volumeCategory)
 * @method string getVolumeCategory()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setVolumeEncrypted($volumeEncrypted)
 * @method bool getVolumeEncrypted()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setKMSKeyId($kMSKeyId)
 * @method string getKMSKeyId()
 */
class CreateVolumes extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setAttributeName($attributeName)
 * @method array getAttributeName()
 */
class DescribeAccountAttributes extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setInstanceCount($instanceCount)
 * @method string getInstanceCount()
 * @method $this setCapacityReservationName($capacityReservationName)
 * @method string getCapacityReservationName()
 * @method $this setInstanceType($instanceType)
 * @method string getInstanceType()
 * @method $this setNetworkType($networkType)
 * @method string getNetworkType()
 * @method $this setInstancePlatform($instancePlatform)
 * @method string getInstancePlatform()
 * @method $this setInstanceMatchCriteria($instanceMatchCriteria)
 * @method string getInstanceMatchCriteria()
 * @method $this setEndDateType($endDateType)
 * @method string getEndDateType()
 * @method $this setTimeSlot($timeSlot)
 * @method string getTimeSlot()
 * @method $this setDescription($description)
 * @method string getDescription()
 */
class CreateCapacityReservation extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setDedicatedHostName($dedicatedHostName)
 * @method string getDedicatedHostName()
 * @method $this setDedicatedHostType($dedicatedHostType)
 * @method string getDedicatedHostType()
 * @method $this setActionOnMaintenance($actionOnMaintenance)
 * @method string getActionOnMaintenance()
 * @method $this setNetworkAttributes_SlbUdpTimeout($networkAttributes_SlbUdpTimeout)
 * @method int getNetworkAttributes_SlbUdpTimeout()
 * @method $this setNetworkAttributes_UdpTimeout($networkAttributes_UdpTimeout)
 * @method int getNetworkAttributes_UdpTimeout()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setChargeType($chargeType)
 * @method string getChargeType()
 * @method $this setQuantity($quantity)
 * @method int getQuantity()
 * @method $this setPeriod($period)
 * @method int getPeriod()
 * @method $this setPeriodUnit($periodUnit)
 * @method string getPeriodUnit()
 * @method $this setAutoRenew($autoRenew)
 * @method bool getAutoRenew()
 * @method $this setAutoRenewPeriod($autoRenewPeriod)
 * @method int getAutoRenewPeriod()
 * @method $this setAutoReleaseTime($autoReleaseTime)
 * @method string getAutoReleaseTime()
 * @method $this setBusinessInfo($businessInfo)
 * @method string getBusinessInfo()
 * @method $this setFromApp($fromApp)
 * @method string getFromApp()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 */
class AllocateDedicatedHosts extends Request
{

}/**
 * @method $this setFilter($filter)
 * @method array getFilter()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeAccountLimits extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setQosGroupName($qosGroupName)
 * @method string getQosGroupName()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class DeleteEniQosGroup extends Request
{

}/**
 * @method $this setDataDisk($dataDisk)
 * @method array getDataDisk()
 * @method $this setNetworkInterface($networkInterface)
 * @method array getNetworkInterface()
 * @method $this setSecurityGroupRule($securityGroupRule)
 * @method array getSecurityGroupRule()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setDefaultVpc($defaultVpc)
 * @method string getDefaultVpc()
 * @method $this setDeploymentSetId($deploymentSetId)
 * @method string getDeploymentSetId()
 * @method $this setNetworkType($networkType)
 * @method string getNetworkType()
 * @method $this setImageId($imageId)
 * @method string getImageId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setClusterId($clusterId)
 * @method string getClusterId()
 * @method $this setInstanceType($instanceType)
 * @method string getInstanceType()
 * @method $this setInternetChargeType($internetChargeType)
 * @method string getInternetChargeType()
 * @method $this setInternetMaxBandwidthOut($internetMaxBandwidthOut)
 * @method int getInternetMaxBandwidthOut()
 * @method $this setInternetMaxBandwidthIn($internetMaxBandwidthIn)
 * @method int getInternetMaxBandwidthIn()
 * @method $this setIoOptimized($ioOptimized)
 * @method string getIoOptimized()
 * @method $this setSystemDisk_Category($systemDisk_Category)
 * @method string getSystemDisk_Category()
 * @method $this setSystemDisk_DiskName($systemDisk_DiskName)
 * @method string getSystemDisk_DiskName()
 * @method $this setSystemDisk_Description($systemDisk_Description)
 * @method string getSystemDisk_Description()
 * @method $this setSystemDisk_Size($systemDisk_Size)
 * @method string getSystemDisk_Size()
 * @method $this setVSwitchId($vSwitchId)
 * @method string getVSwitchId()
 * @method $this setMinAmount($minAmount)
 * @method int getMinAmount()
 * @method $this setMaxAmount($maxAmount)
 * @method int getMaxAmount()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setSecurityGroupId($securityGroupId)
 * @method string getSecurityGroupId()
 * @method $this setInstanceName($instanceName)
 * @method string getInstanceName()
 * @method $this setHostName($hostName)
 * @method string getHostName()
 * @method $this setUniqueSuffix($uniqueSuffix)
 * @method bool getUniqueSuffix()
 * @method $this setPassword($password)
 * @method string getPassword()
 * @method $this setPasswordInherit($passwordInherit)
 * @method bool getPasswordInherit()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setAutoReleaseTime($autoReleaseTime)
 * @method string getAutoReleaseTime()
 * @method $this setFromApp($fromApp)
 * @method string getFromApp()
 * @method $this setNodeControllerId($nodeControllerId)
 * @method string getNodeControllerId()
 * @method $this setRelationOrderId($relationOrderId)
 * @method string getRelationOrderId()
 * @method $this setBusinessInfo($businessInfo)
 * @method string getBusinessInfo()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setUserData($userData)
 * @method string getUserData()
 * @method $this setSpotStrategy($spotStrategy)
 * @method string getSpotStrategy()
 * @method $this setKeyPairName($keyPairName)
 * @method string getKeyPairName()
 * @method $this setSpotPriceLimit($spotPriceLimit)
 * @method Float getSpotPriceLimit()
 * @method $this setSpotInterruptionBehavior($spotInterruptionBehavior)
 * @method string getSpotInterruptionBehavior()
 * @method $this setRamRoleName($ramRoleName)
 * @method string getRamRoleName()
 * @method $this setSecurityEnhancementStrategy($securityEnhancementStrategy)
 * @method string getSecurityEnhancementStrategy()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setHpcClusterId($hpcClusterId)
 * @method string getHpcClusterId()
 * @method $this setRecycleBinResourceId($recycleBinResourceId)
 * @method string getRecycleBinResourceId()
 * @method $this setDryRun($dryRun)
 * @method bool getDryRun()
 * @method $this setDedicatedHostId($dedicatedHostId)
 * @method string getDedicatedHostId()
 * @method $this setCreditSpecification($creditSpecification)
 * @method string getCreditSpecification()
 * @method $this setIpv6Address($ipv6Address)
 * @method array getIpv6Address()
 * @method $this setIpv6AddressCount($ipv6AddressCount)
 * @method int getIpv6AddressCount()
 * @method $this setDeletionProtection($deletionProtection)
 * @method bool getDeletionProtection()
 * @method $this setCapacityReservationId($capacityReservationId)
 * @method string getCapacityReservationId()
 * @method $this setCapacityReservationPreference($capacityReservationPreference)
 * @method string getCapacityReservationPreference()
 */
class RunInstances extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setNetworkInterfaceId($networkInterfaceId)
 * @method string getNetworkInterfaceId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class QueryEniQosGroupByEni extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setDedicatedHostId($dedicatedHostId)
 * @method string getDedicatedHostId()
 * @method $this setToken($token)
 * @method string getToken()
 * @method $this setForce($force)
 * @method bool getForce()
 */
class ReleaseDedicatedHost extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOrderType($orderType)
 * @method string getOrderType()
 * @method $this setChargeType($chargeType)
 * @method string getChargeType()
 * @method $this setCommodity($commodity)
 * @method string getCommodity()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setBusinessInfo($businessInfo)
 * @method string getBusinessInfo()
 * @method $this setFromApp($fromApp)
 * @method string getFromApp()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setDedicatedHostId($dedicatedHostId)
 * @method string getDedicatedHostId()
 * @method $this setAsyncPattern($asyncPattern)
 * @method bool getAsyncPattern()
 */
class CreateOrder extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setName($name)
 * @method array getName()
 */
class DeleteConfigLogSubscriptions extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setSubscription($subscription)
 * @method array getSubscription()
 */
class CreateConfigLogSubscriptions extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setDefaultVpc($defaultVpc)
 * @method string getDefaultVpc()
 * @method $this setNetworkType($networkType)
 * @method string getNetworkType()
 * @method $this setOrderType($orderType)
 * @method string getOrderType()
 * @method $this setCommodity($commodity)
 * @method string getCommodity()
 * @method $this setVerbose($verbose)
 * @method bool getVerbose()
 * @method $this setNeedSpotPrice($needSpotPrice)
 * @method bool getNeedSpotPrice()
 * @method $this setBusinessInfo($businessInfo)
 * @method string getBusinessInfo()
 * @method $this setFromApp($fromApp)
 * @method string getFromApp()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribePrice extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setNetworkInterfaceId($networkInterfaceId)
 * @method string getNetworkInterfaceId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class LeaveEniQosGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setInstanceId($instanceId)
 * @method string getInstanceId()
 * @method $this setDedicatedHostId($dedicatedHostId)
 * @method string getDedicatedHostId()
 */
class ModifyInstanceDeployment extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setappKey($appKey)
 * @method string getappKey()
 * @method $this settoken($token)
 * @method string gettoken()
 * @method $this setproxyId($proxyId)
 * @method string getproxyId()
 * @method $this setchannel($channel)
 * @method string getchannel()
 * @method $this setoperator($operator)
 * @method string getoperator()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPageSize($pageSize)
 * @method string getPageSize()
 * @method $this setPageNumber($pageNumber)
 * @method string getPageNumber()
 */
class DescribeKMSKeys extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setInstanceId($instanceId)
 * @method string getInstanceId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class QueryEniQosGroupByInstance extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setReservedInstanceId($reservedInstanceId)
 * @method array getReservedInstanceId()
 * @method $this setConfiguration($configuration)
 * @method array getConfiguration()
 */
class ModifyReservedInstances extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setInstanceIds($instanceIds)
 * @method array getInstanceIds()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 */
class DescribeInstanceNeedReboot extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTemplateTag($templateTag)
 * @method array getTemplateTag()
 * @method $this setProduct($product)
 * @method string getProduct()
 * @method $this setResourceType($resourceType)
 * @method string getResourceType()
 * @method $this setGlobal($global)
 * @method string getGlobal()
 * @method $this setRegionNo($regionNo)
 * @method string getRegionNo()
 * @method $this setAttributeName($attributeName)
 * @method string getAttributeName()
 * @method $this setAttributeValue($attributeValue)
 * @method string getAttributeValue()
 * @method $this setMaxItems($maxItems)
 * @method int getMaxItems()
 */
class DescribeResourceRecommendFilters extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setReservedInstanceId($reservedInstanceId)
 * @method array getReservedInstanceId()
 * @method $this setReservedInstanceName($reservedInstanceName)
 * @method string getReservedInstanceName()
 * @method $this setStatus($status)
 * @method array getStatus()
 * @method $this setLockReason($lockReason)
 * @method string getLockReason()
 * @method $this setInstanceType($instanceType)
 * @method string getInstanceType()
 * @method $this setInstanceTypeFamily($instanceTypeFamily)
 * @method string getInstanceTypeFamily()
 * @method $this setScope($scope)
 * @method string getScope()
 * @method $this setOfferingType($offeringType)
 * @method string getOfferingType()
 * @method $this setExpiredTime($expiredTime)
 * @method string getExpiredTime()
 */
class DescribeReservedInstances extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setQosGroupName($qosGroupName)
 * @method string getQosGroupName()
 * @method $this setNetworkInterfaceId($networkInterfaceId)
 * @method string getNetworkInterfaceId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class JoinEniQosGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setappKey($appKey)
 * @method string getappKey()
 * @method $this settoken($token)
 * @method string gettoken()
 * @method $this setproxyId($proxyId)
 * @method string getproxyId()
 * @method $this setchannel($channel)
 * @method string getchannel()
 * @method $this setoperator($operator)
 * @method string getoperator()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class DescribeLinkedKMSKeys extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setSnapshotId($snapshotId)
 * @method string getSnapshotId()
 * @method $this setVolumeName($volumeName)
 * @method string getVolumeName()
 * @method $this setSize($size)
 * @method int getSize()
 * @method $this setAmount($amount)
 * @method int getAmount()
 * @method $this setVolumeCategory($volumeCategory)
 * @method string getVolumeCategory()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setTag($tag)
 * @method array getTag()
 */
class CreateVolumes_GatedLaunch extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setCapacityReservationId($capacityReservationId)
 * @method string getCapacityReservationId()
 * @method $this setToken($token)
 * @method string getToken()
 */
class ReleaseCapacityReservation extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setInstanceId($instanceId)
 * @method string getInstanceId()
 */
class GetLaunchTemplateData extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setDedicatedHostType($dedicatedHostType)
 * @method string getDedicatedHostType()
 * @method $this setSupportInstanceTypeFamily($supportInstanceTypeFamily)
 * @method string getSupportInstanceTypeFamily()
 * @method $this setGeneration($generation)
 * @method string getGeneration()
 */
class DescribeDedicatedHostTypes extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setReservedInstanceName($reservedInstanceName)
 * @method string getReservedInstanceName()
 * @method $this setInstanceType($instanceType)
 * @method string getInstanceType()
 * @method $this setScope($scope)
 * @method string getScope()
 * @method $this setInstanceAmount($instanceAmount)
 * @method int getInstanceAmount()
 * @method $this setOfferingType($offeringType)
 * @method string getOfferingType()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setChargeType($chargeType)
 * @method string getChargeType()
 * @method $this setPeriod($period)
 * @method int getPeriod()
 * @method $this setPeriodUnit($periodUnit)
 * @method string getPeriodUnit()
 * @method $this setBusinessInfo($businessInfo)
 * @method string getBusinessInfo()
 * @method $this setFromApp($fromApp)
 * @method string getFromApp()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setAutoPay($autoPay)
 * @method bool getAutoPay()
 */
class PurchaseReservedInstancesOffering extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setInstanceIds($instanceIds)
 * @method string getInstanceIds()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setResourceType($resourceType)
 * @method string getResourceType()
 * @method $this setDuration($duration)
 * @method int getDuration()
 * @method $this setPeriodUnit($periodUnit)
 * @method string getPeriodUnit()
 * @method $this setAutoRenew($autoRenew)
 * @method bool getAutoRenew()
 * @method $this setRenewalStatus($renewalStatus)
 * @method string getRenewalStatus()
 */
class ModifyDedicatedHostAutoRenewAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setDedicatedHostIds($dedicatedHostIds)
 * @method string getDedicatedHostIds()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPeriod($period)
 * @method int getPeriod()
 * @method $this setPeriodUnit($periodUnit)
 * @method string getPeriodUnit()
 * @method $this setBusinessInfo($businessInfo)
 * @method string getBusinessInfo()
 * @method $this setFromApp($fromApp)
 * @method string getFromApp()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 */
class RenewDedicatedHosts extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setName($name)
 * @method array getName()
 * @method $this setResourceType($resourceType)
 * @method array getResourceType()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 */
class DescribeConfigLogSubscription extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setInstanceId($instanceId)
 * @method string getInstanceId()
 * @method $this setAutoReleaseTime($autoReleaseTime)
 * @method string getAutoReleaseTime()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class SetInstanceAutoReleaseTime extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setDedicatedHostIds($dedicatedHostIds)
 * @method string getDedicatedHostIds()
 * @method $this setDedicatedHostName($dedicatedHostName)
 * @method string getDedicatedHostName()
 * @method $this setStatus($status)
 * @method string getStatus()
 * @method $this setDedicatedHostType($dedicatedHostType)
 * @method string getDedicatedHostType()
 * @method $this setLockReason($lockReason)
 * @method string getLockReason()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 */
class DescribeDedicatedHosts extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setDedicatedHostId($dedicatedHostId)
 * @method string getDedicatedHostId()
 * @method $this setDedicatedHostName($dedicatedHostName)
 * @method string getDedicatedHostName()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setActionOnMaintenance($actionOnMaintenance)
 * @method string getActionOnMaintenance()
 * @method $this setNetworkAttributes_SlbUdpTimeout($networkAttributes_SlbUdpTimeout)
 * @method int getNetworkAttributes_SlbUdpTimeout()
 * @method $this setNetworkAttributes_UdpTimeout($networkAttributes_UdpTimeout)
 * @method int getNetworkAttributes_UdpTimeout()
 */
class ModifyDedicatedHostAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setInstanceIds($instanceIds)
 * @method string getInstanceIds()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setResourceType($resourceType)
 * @method string getResourceType()
 */
class DescribeDedicatedHostAutoRenew extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setSize($size)
 * @method int getSize()
 * @method $this setSnapshotId($snapshotId)
 * @method string getSnapshotId()
 * @method $this setCategory($category)
 * @method string getCategory()
 * @method $this setDiskName($diskName)
 * @method string getDiskName()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setEncrypted($encrypted)
 * @method bool getEncrypted()
 * @method $this setAmount($amount)
 * @method int getAmount()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setKMSKeyId($kMSKeyId)
 * @method string getKMSKeyId()
 */
class CreateDisks extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setReservedInstanceId($reservedInstanceId)
 * @method array getReservedInstanceId()
 */
class DescribeReservedInstancePrice extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTemplateTag($templateTag)
 * @method array getTemplateTag()
 * @method $this setProduct($product)
 * @method string getProduct()
 * @method $this setResourceType($resourceType)
 * @method string getResourceType()
 */
class DescribeResourceFilterAttributes extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTemplateTag($templateTag)
 * @method array getTemplateTag()
 * @method $this setProduct($product)
 * @method string getProduct()
 * @method $this setResourceType($resourceType)
 * @method string getResourceType()
 * @method $this setGlobal($global)
 * @method string getGlobal()
 * @method $this setRegionNo($regionNo)
 * @method string getRegionNo()
 * @method $this setFilter($filter)
 * @method array getFilter()
 * @method $this setMarker($marker)
 * @method string getMarker()
 * @method $this setMaxItems($maxItems)
 * @method int getMaxItems()
 * @method $this setKeyword($keyword)
 * @method string getKeyword()
 */
class DescribeResources extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPriceUnit($priceUnit)
 * @method string getPriceUnit()
 * @method $this setVerbose($verbose)
 * @method bool getVerbose()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeBandwidthPrice extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setQosGroupName($qosGroupName)
 * @method string getQosGroupName()
 * @method $this setInstanceId($instanceId)
 * @method string getInstanceId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setRx($rx)
 * @method int getRx()
 * @method $this setRxPps($rxPps)
 * @method int getRxPps()
 * @method $this setTx($tx)
 * @method int getTx()
 * @method $this setTxPps($txPps)
 * @method int getTxPps()
 */
class CreateEniQosGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setappKey($appKey)
 * @method string getappKey()
 * @method $this settoken($token)
 * @method string gettoken()
 * @method $this setproxyId($proxyId)
 * @method string getproxyId()
 * @method $this setchannel($channel)
 * @method string getchannel()
 * @method $this setoperator($operator)
 * @method string getoperator()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setKMSKeyId($kMSKeyId)
 * @method string getKMSKeyId()
 */
class DescribeKMSKeyAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setCapacityReservationIds($capacityReservationIds)
 * @method string getCapacityReservationIds()
 * @method $this setCapacityReservationName($capacityReservationName)
 * @method string getCapacityReservationName()
 * @method $this setStatus($status)
 * @method string getStatus()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 */
class DescribeCapacityReservations extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setQosGroupName($qosGroupName)
 * @method string getQosGroupName()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class DescribeEniQosGroupInfo extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setZoneId($zoneId)
 * @method string getZoneId()
 * @method $this setSize($size)
 * @method int getSize()
 * @method $this setSnapshotId($snapshotId)
 * @method string getSnapshotId()
 * @method $this setCategory($category)
 * @method string getCategory()
 * @method $this setDiskName($diskName)
 * @method string getDiskName()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setAmount($amount)
 * @method int getAmount()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class CreateDisks_GatedLaunch extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setInstanceId($instanceId)
 * @method string getInstanceId()
 * @method $this setAutoReleaseTime($autoReleaseTime)
 * @method string getAutoReleaseTime()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class ModifyDedicatedHostAutoReleaseTime extends Request
{

}