<?php

namespace aliyun\sdk\services\Ess20160722;

use aliyun\sdk\core\lib\Request;

/**
 * Class V20160722
 *
 * @package aliyun\sdk\services\Ess20160722
 * @method ModifyScalingGroup ModifyScalingGroup()
 * @method DescribeScalingActivityDetail DescribeScalingActivityDetail()
 * @method DescribeCapacityHistory DescribeCapacityHistory()
 * @method DescribeAccountAttributes DescribeAccountAttributes()
 * @method DescribeScalingGroups DescribeScalingGroups()
 * @method CreateScalingRule CreateScalingRule()
 * @method DeleteScalingConfiguration DeleteScalingConfiguration()
 * @method EnableScalingGroup EnableScalingGroup()
 * @method ExecuteScalingRule ExecuteScalingRule()
 * @method DescribeScalingInstances DescribeScalingInstances()
 * @method ModifyScheduledTask ModifyScheduledTask()
 * @method VerifyUser VerifyUser()
 * @method DeleteScheduledTask DeleteScheduledTask()
 * @method DescribeRegions DescribeRegions()
 * @method DescribeLimitation DescribeLimitation()
 * @method DescribeScalingActivities DescribeScalingActivities()
 * @method RemoveInstances RemoveInstances()
 * @method DescribeScalingConfigurations DescribeScalingConfigurations()
 * @method VerifyAuthentication VerifyAuthentication()
 * @method CreateScalingConfiguration CreateScalingConfiguration()
 * @method DescribeScheduledTasks DescribeScheduledTasks()
 * @method CreateScheduledTask CreateScheduledTask()
 * @method DetachInstances DetachInstances()
 * @method DescribeScalingRules DescribeScalingRules()
 * @method DeleteScalingRule DeleteScalingRule()
 * @method DisableScalingGroup DisableScalingGroup()
 * @method AttachInstances AttachInstances()
 * @method DeleteScalingGroup DeleteScalingGroup()
 * @method CreateScalingGroup CreateScalingGroup()
 * @method ModifyScalingRule ModifyScalingRule()
 */
class V20160722
{
}

/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setScalingGroupName($scalingGroupName)
 * @method string getScalingGroupName()
 * @method $this setMinSize($minSize)
 * @method int getMinSize()
 * @method $this setMaxSize($maxSize)
 * @method int getMaxSize()
 * @method $this setDefaultCooldown($defaultCooldown)
 * @method int getDefaultCooldown()
 * @method $this setRemovalPolicy_1($removalPolicy_1)
 * @method string getRemovalPolicy_1()
 * @method $this setRemovalPolicy_2($removalPolicy_2)
 * @method string getRemovalPolicy_2()
 * @method $this setActiveScalingConfigurationId($activeScalingConfigurationId)
 * @method string getActiveScalingConfigurationId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class ModifyScalingGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingActivityId($scalingActivityId)
 * @method string getScalingActivityId()
 */
class DescribeScalingActivityDetail extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setStartTime($startTime)
 * @method string getStartTime()
 * @method $this setEndTime($endTime)
 * @method string getEndTime()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 */
class DescribeCapacityHistory extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 */
class DescribeAccountAttributes extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setScalingGroupId_1($scalingGroupId_1)
 * @method string getScalingGroupId_1()
 * @method $this setScalingGroupId_2($scalingGroupId_2)
 * @method string getScalingGroupId_2()
 * @method $this setScalingGroupId_3($scalingGroupId_3)
 * @method string getScalingGroupId_3()
 * @method $this setScalingGroupId_4($scalingGroupId_4)
 * @method string getScalingGroupId_4()
 * @method $this setScalingGroupId_5($scalingGroupId_5)
 * @method string getScalingGroupId_5()
 * @method $this setScalingGroupId_6($scalingGroupId_6)
 * @method string getScalingGroupId_6()
 * @method $this setScalingGroupId_7($scalingGroupId_7)
 * @method string getScalingGroupId_7()
 * @method $this setScalingGroupId_8($scalingGroupId_8)
 * @method string getScalingGroupId_8()
 * @method $this setScalingGroupId_9($scalingGroupId_9)
 * @method string getScalingGroupId_9()
 * @method $this setScalingGroupId_10($scalingGroupId_10)
 * @method string getScalingGroupId_10()
 * @method $this setScalingGroupId_12($scalingGroupId_12)
 * @method string getScalingGroupId_12()
 * @method $this setScalingGroupId_13($scalingGroupId_13)
 * @method string getScalingGroupId_13()
 * @method $this setScalingGroupId_14($scalingGroupId_14)
 * @method string getScalingGroupId_14()
 * @method $this setScalingGroupId_15($scalingGroupId_15)
 * @method string getScalingGroupId_15()
 * @method $this setScalingGroupId_16($scalingGroupId_16)
 * @method string getScalingGroupId_16()
 * @method $this setScalingGroupId_17($scalingGroupId_17)
 * @method string getScalingGroupId_17()
 * @method $this setScalingGroupId_18($scalingGroupId_18)
 * @method string getScalingGroupId_18()
 * @method $this setScalingGroupId_19($scalingGroupId_19)
 * @method string getScalingGroupId_19()
 * @method $this setScalingGroupId_20($scalingGroupId_20)
 * @method string getScalingGroupId_20()
 * @method $this setScalingGroupName_1($scalingGroupName_1)
 * @method string getScalingGroupName_1()
 * @method $this setScalingGroupName_2($scalingGroupName_2)
 * @method string getScalingGroupName_2()
 * @method $this setScalingGroupName_3($scalingGroupName_3)
 * @method string getScalingGroupName_3()
 * @method $this setScalingGroupName_4($scalingGroupName_4)
 * @method string getScalingGroupName_4()
 * @method $this setScalingGroupName_5($scalingGroupName_5)
 * @method string getScalingGroupName_5()
 * @method $this setScalingGroupName_6($scalingGroupName_6)
 * @method string getScalingGroupName_6()
 * @method $this setScalingGroupName_7($scalingGroupName_7)
 * @method string getScalingGroupName_7()
 * @method $this setScalingGroupName_8($scalingGroupName_8)
 * @method string getScalingGroupName_8()
 * @method $this setScalingGroupName_9($scalingGroupName_9)
 * @method string getScalingGroupName_9()
 * @method $this setScalingGroupName_10($scalingGroupName_10)
 * @method string getScalingGroupName_10()
 * @method $this setScalingGroupName_11($scalingGroupName_11)
 * @method string getScalingGroupName_11()
 * @method $this setScalingGroupName_12($scalingGroupName_12)
 * @method string getScalingGroupName_12()
 * @method $this setScalingGroupName_13($scalingGroupName_13)
 * @method string getScalingGroupName_13()
 * @method $this setScalingGroupName_14($scalingGroupName_14)
 * @method string getScalingGroupName_14()
 * @method $this setScalingGroupName_15($scalingGroupName_15)
 * @method string getScalingGroupName_15()
 * @method $this setScalingGroupName_16($scalingGroupName_16)
 * @method string getScalingGroupName_16()
 * @method $this setScalingGroupName_17($scalingGroupName_17)
 * @method string getScalingGroupName_17()
 * @method $this setScalingGroupName_18($scalingGroupName_18)
 * @method string getScalingGroupName_18()
 * @method $this setScalingGroupName_19($scalingGroupName_19)
 * @method string getScalingGroupName_19()
 * @method $this setScalingGroupName_20($scalingGroupName_20)
 * @method string getScalingGroupName_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeScalingGroups extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setScalingRuleName($scalingRuleName)
 * @method string getScalingRuleName()
 * @method $this setCooldown($cooldown)
 * @method int getCooldown()
 * @method $this setAdjustmentType($adjustmentType)
 * @method string getAdjustmentType()
 * @method $this setAdjustmentValue($adjustmentValue)
 * @method int getAdjustmentValue()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class CreateScalingRule extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingConfigurationId($scalingConfigurationId)
 * @method string getScalingConfigurationId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DeleteScalingConfiguration extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setActiveScalingConfigurationId($activeScalingConfigurationId)
 * @method string getActiveScalingConfigurationId()
 * @method $this setInstanceId_1($instanceId_1)
 * @method string getInstanceId_1()
 * @method $this setInstanceId_2($instanceId_2)
 * @method string getInstanceId_2()
 * @method $this setInstanceId_3($instanceId_3)
 * @method string getInstanceId_3()
 * @method $this setInstanceId_4($instanceId_4)
 * @method string getInstanceId_4()
 * @method $this setInstanceId_5($instanceId_5)
 * @method string getInstanceId_5()
 * @method $this setInstanceId_6($instanceId_6)
 * @method string getInstanceId_6()
 * @method $this setInstanceId_7($instanceId_7)
 * @method string getInstanceId_7()
 * @method $this setInstanceId_8($instanceId_8)
 * @method string getInstanceId_8()
 * @method $this setInstanceId_9($instanceId_9)
 * @method string getInstanceId_9()
 * @method $this setInstanceId_10($instanceId_10)
 * @method string getInstanceId_10()
 * @method $this setInstanceId_11($instanceId_11)
 * @method string getInstanceId_11()
 * @method $this setInstanceId_12($instanceId_12)
 * @method string getInstanceId_12()
 * @method $this setInstanceId_13($instanceId_13)
 * @method string getInstanceId_13()
 * @method $this setInstanceId_14($instanceId_14)
 * @method string getInstanceId_14()
 * @method $this setInstanceId_15($instanceId_15)
 * @method string getInstanceId_15()
 * @method $this setInstanceId_16($instanceId_16)
 * @method string getInstanceId_16()
 * @method $this setInstanceId_17($instanceId_17)
 * @method string getInstanceId_17()
 * @method $this setInstanceId_18($instanceId_18)
 * @method string getInstanceId_18()
 * @method $this setInstanceId_19($instanceId_19)
 * @method string getInstanceId_19()
 * @method $this setInstanceId_20($instanceId_20)
 * @method string getInstanceId_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class EnableScalingGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingRuleAri($scalingRuleAri)
 * @method string getScalingRuleAri()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class ExecuteScalingRule extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setScalingConfigurationId($scalingConfigurationId)
 * @method string getScalingConfigurationId()
 * @method $this setHealthStatus($healthStatus)
 * @method string getHealthStatus()
 * @method $this setLifecycleState($lifecycleState)
 * @method string getLifecycleState()
 * @method $this setCreationType($creationType)
 * @method string getCreationType()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setInstanceId_1($instanceId_1)
 * @method string getInstanceId_1()
 * @method $this setInstanceId_2($instanceId_2)
 * @method string getInstanceId_2()
 * @method $this setInstanceId_3($instanceId_3)
 * @method string getInstanceId_3()
 * @method $this setInstanceId_4($instanceId_4)
 * @method string getInstanceId_4()
 * @method $this setInstanceId_5($instanceId_5)
 * @method string getInstanceId_5()
 * @method $this setInstanceId_6($instanceId_6)
 * @method string getInstanceId_6()
 * @method $this setInstanceId_7($instanceId_7)
 * @method string getInstanceId_7()
 * @method $this setInstanceId_8($instanceId_8)
 * @method string getInstanceId_8()
 * @method $this setInstanceId_9($instanceId_9)
 * @method string getInstanceId_9()
 * @method $this setInstanceId_10($instanceId_10)
 * @method string getInstanceId_10()
 * @method $this setInstanceId_11($instanceId_11)
 * @method string getInstanceId_11()
 * @method $this setInstanceId_12($instanceId_12)
 * @method string getInstanceId_12()
 * @method $this setInstanceId_13($instanceId_13)
 * @method string getInstanceId_13()
 * @method $this setInstanceId_14($instanceId_14)
 * @method string getInstanceId_14()
 * @method $this setInstanceId_15($instanceId_15)
 * @method string getInstanceId_15()
 * @method $this setInstanceId_16($instanceId_16)
 * @method string getInstanceId_16()
 * @method $this setInstanceId_17($instanceId_17)
 * @method string getInstanceId_17()
 * @method $this setInstanceId_18($instanceId_18)
 * @method string getInstanceId_18()
 * @method $this setInstanceId_19($instanceId_19)
 * @method string getInstanceId_19()
 * @method $this setInstanceId_20($instanceId_20)
 * @method string getInstanceId_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeScalingInstances extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScheduledTaskId($scheduledTaskId)
 * @method string getScheduledTaskId()
 * @method $this setScheduledTaskName($scheduledTaskName)
 * @method string getScheduledTaskName()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setScheduledAction($scheduledAction)
 * @method string getScheduledAction()
 * @method $this setRecurrenceEndTime($recurrenceEndTime)
 * @method string getRecurrenceEndTime()
 * @method $this setLaunchTime($launchTime)
 * @method string getLaunchTime()
 * @method $this setRecurrenceType($recurrenceType)
 * @method string getRecurrenceType()
 * @method $this setRecurrenceValue($recurrenceValue)
 * @method string getRecurrenceValue()
 * @method $this setTaskEnabled($taskEnabled)
 * @method bool getTaskEnabled()
 * @method $this setLaunchExpirationTime($launchExpirationTime)
 * @method int getLaunchExpirationTime()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class ModifyScheduledTask extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 */
class VerifyUser extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScheduledTaskId($scheduledTaskId)
 * @method string getScheduledTaskId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DeleteScheduledTask extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 */
class DescribeRegions extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 */
class DescribeLimitation extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setStatusCode($statusCode)
 * @method string getStatusCode()
 * @method $this setScalingActivityId_1($scalingActivityId_1)
 * @method string getScalingActivityId_1()
 * @method $this setScalingActivityId_2($scalingActivityId_2)
 * @method string getScalingActivityId_2()
 * @method $this setScalingActivityId_3($scalingActivityId_3)
 * @method string getScalingActivityId_3()
 * @method $this setScalingActivityId_4($scalingActivityId_4)
 * @method string getScalingActivityId_4()
 * @method $this setScalingActivityId_5($scalingActivityId_5)
 * @method string getScalingActivityId_5()
 * @method $this setScalingActivityId_6($scalingActivityId_6)
 * @method string getScalingActivityId_6()
 * @method $this setScalingActivityId_7($scalingActivityId_7)
 * @method string getScalingActivityId_7()
 * @method $this setScalingActivityId_8($scalingActivityId_8)
 * @method string getScalingActivityId_8()
 * @method $this setScalingActivityId_9($scalingActivityId_9)
 * @method string getScalingActivityId_9()
 * @method $this setScalingActivityId_10($scalingActivityId_10)
 * @method string getScalingActivityId_10()
 * @method $this setScalingActivityId_11($scalingActivityId_11)
 * @method string getScalingActivityId_11()
 * @method $this setScalingActivityId_12($scalingActivityId_12)
 * @method string getScalingActivityId_12()
 * @method $this setScalingActivityId_13($scalingActivityId_13)
 * @method string getScalingActivityId_13()
 * @method $this setScalingActivityId_14($scalingActivityId_14)
 * @method string getScalingActivityId_14()
 * @method $this setScalingActivityId_15($scalingActivityId_15)
 * @method string getScalingActivityId_15()
 * @method $this setScalingActivityId_16($scalingActivityId_16)
 * @method string getScalingActivityId_16()
 * @method $this setScalingActivityId_17($scalingActivityId_17)
 * @method string getScalingActivityId_17()
 * @method $this setScalingActivityId_18($scalingActivityId_18)
 * @method string getScalingActivityId_18()
 * @method $this setScalingActivityId_19($scalingActivityId_19)
 * @method string getScalingActivityId_19()
 * @method $this setScalingActivityId_20($scalingActivityId_20)
 * @method string getScalingActivityId_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeScalingActivities extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setInstanceId_1($instanceId_1)
 * @method string getInstanceId_1()
 * @method $this setInstanceId_2($instanceId_2)
 * @method string getInstanceId_2()
 * @method $this setInstanceId_3($instanceId_3)
 * @method string getInstanceId_3()
 * @method $this setInstanceId_4($instanceId_4)
 * @method string getInstanceId_4()
 * @method $this setInstanceId_5($instanceId_5)
 * @method string getInstanceId_5()
 * @method $this setInstanceId_6($instanceId_6)
 * @method string getInstanceId_6()
 * @method $this setInstanceId_7($instanceId_7)
 * @method string getInstanceId_7()
 * @method $this setInstanceId_8($instanceId_8)
 * @method string getInstanceId_8()
 * @method $this setInstanceId_9($instanceId_9)
 * @method string getInstanceId_9()
 * @method $this setInstanceId_10($instanceId_10)
 * @method string getInstanceId_10()
 * @method $this setInstanceId_11($instanceId_11)
 * @method string getInstanceId_11()
 * @method $this setInstanceId_12($instanceId_12)
 * @method string getInstanceId_12()
 * @method $this setInstanceId_13($instanceId_13)
 * @method string getInstanceId_13()
 * @method $this setInstanceId_14($instanceId_14)
 * @method string getInstanceId_14()
 * @method $this setInstanceId_15($instanceId_15)
 * @method string getInstanceId_15()
 * @method $this setInstanceId_16($instanceId_16)
 * @method string getInstanceId_16()
 * @method $this setInstanceId_17($instanceId_17)
 * @method string getInstanceId_17()
 * @method $this setInstanceId_18($instanceId_18)
 * @method string getInstanceId_18()
 * @method $this setInstanceId_19($instanceId_19)
 * @method string getInstanceId_19()
 * @method $this setInstanceId_20($instanceId_20)
 * @method string getInstanceId_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class RemoveInstances extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setScalingConfigurationId_1($scalingConfigurationId_1)
 * @method string getScalingConfigurationId_1()
 * @method $this setScalingConfigurationId_2($scalingConfigurationId_2)
 * @method string getScalingConfigurationId_2()
 * @method $this setScalingConfigurationId_3($scalingConfigurationId_3)
 * @method string getScalingConfigurationId_3()
 * @method $this setScalingConfigurationId_4($scalingConfigurationId_4)
 * @method string getScalingConfigurationId_4()
 * @method $this setScalingConfigurationId_5($scalingConfigurationId_5)
 * @method string getScalingConfigurationId_5()
 * @method $this setScalingConfigurationId_6($scalingConfigurationId_6)
 * @method string getScalingConfigurationId_6()
 * @method $this setScalingConfigurationId_7($scalingConfigurationId_7)
 * @method string getScalingConfigurationId_7()
 * @method $this setScalingConfigurationId_8($scalingConfigurationId_8)
 * @method string getScalingConfigurationId_8()
 * @method $this setScalingConfigurationId_9($scalingConfigurationId_9)
 * @method string getScalingConfigurationId_9()
 * @method $this setScalingConfigurationId_10($scalingConfigurationId_10)
 * @method string getScalingConfigurationId_10()
 * @method $this setScalingConfigurationName_1($scalingConfigurationName_1)
 * @method string getScalingConfigurationName_1()
 * @method $this setScalingConfigurationName_2($scalingConfigurationName_2)
 * @method string getScalingConfigurationName_2()
 * @method $this setScalingConfigurationName_3($scalingConfigurationName_3)
 * @method string getScalingConfigurationName_3()
 * @method $this setScalingConfigurationName_4($scalingConfigurationName_4)
 * @method string getScalingConfigurationName_4()
 * @method $this setScalingConfigurationName_5($scalingConfigurationName_5)
 * @method string getScalingConfigurationName_5()
 * @method $this setScalingConfigurationName_6($scalingConfigurationName_6)
 * @method string getScalingConfigurationName_6()
 * @method $this setScalingConfigurationName_7($scalingConfigurationName_7)
 * @method string getScalingConfigurationName_7()
 * @method $this setScalingConfigurationName_8($scalingConfigurationName_8)
 * @method string getScalingConfigurationName_8()
 * @method $this setScalingConfigurationName_9($scalingConfigurationName_9)
 * @method string getScalingConfigurationName_9()
 * @method $this setScalingConfigurationName_10($scalingConfigurationName_10)
 * @method string getScalingConfigurationName_10()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeScalingConfigurations extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setUid($uid)
 * @method int getUid()
 */
class VerifyAuthentication extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setImageId($imageId)
 * @method string getImageId()
 * @method $this setInstanceType($instanceType)
 * @method string getInstanceType()
 * @method $this setSecurityGroupId($securityGroupId)
 * @method string getSecurityGroupId()
 * @method $this setIoOptimized($ioOptimized)
 * @method string getIoOptimized()
 * @method $this setInternetChargeType($internetChargeType)
 * @method string getInternetChargeType()
 * @method $this setInternetMaxBandwidthIn($internetMaxBandwidthIn)
 * @method int getInternetMaxBandwidthIn()
 * @method $this setInternetMaxBandwidthOut($internetMaxBandwidthOut)
 * @method int getInternetMaxBandwidthOut()
 * @method $this setSystemDisk_Category($systemDisk_Category)
 * @method string getSystemDisk_Category()
 * @method $this setSystemDisk_Size($systemDisk_Size)
 * @method int getSystemDisk_Size()
 * @method $this setScalingConfigurationName($scalingConfigurationName)
 * @method string getScalingConfigurationName()
 * @method $this setDataDisk_1_Size($dataDisk_1_Size)
 * @method int getDataDisk_1_Size()
 * @method $this setDataDisk_2_Size($dataDisk_2_Size)
 * @method int getDataDisk_2_Size()
 * @method $this setDataDisk_3_Size($dataDisk_3_Size)
 * @method int getDataDisk_3_Size()
 * @method $this setDataDisk_4_Size($dataDisk_4_Size)
 * @method int getDataDisk_4_Size()
 * @method $this setDataDisk_1_Category($dataDisk_1_Category)
 * @method string getDataDisk_1_Category()
 * @method $this setDataDisk_2_Category($dataDisk_2_Category)
 * @method string getDataDisk_2_Category()
 * @method $this setDataDisk_3_Category($dataDisk_3_Category)
 * @method string getDataDisk_3_Category()
 * @method $this setDataDisk_4_Category($dataDisk_4_Category)
 * @method string getDataDisk_4_Category()
 * @method $this setDataDisk_1_SnapshotId($dataDisk_1_SnapshotId)
 * @method string getDataDisk_1_SnapshotId()
 * @method $this setDataDisk_2_SnapshotId($dataDisk_2_SnapshotId)
 * @method string getDataDisk_2_SnapshotId()
 * @method $this setDataDisk_3_SnapshotId($dataDisk_3_SnapshotId)
 * @method string getDataDisk_3_SnapshotId()
 * @method $this setDataDisk_4_SnapshotId($dataDisk_4_SnapshotId)
 * @method string getDataDisk_4_SnapshotId()
 * @method $this setDataDisk_1_Device($dataDisk_1_Device)
 * @method string getDataDisk_1_Device()
 * @method $this setDataDisk_2_Device($dataDisk_2_Device)
 * @method string getDataDisk_2_Device()
 * @method $this setDataDisk_3_Device($dataDisk_3_Device)
 * @method string getDataDisk_3_Device()
 * @method $this setDataDisk_4_Device($dataDisk_4_Device)
 * @method string getDataDisk_4_Device()
 * @method $this setDataDisk_1_DeleteWithInstance($dataDisk_1_DeleteWithInstance)
 * @method string getDataDisk_1_DeleteWithInstance()
 * @method $this setDataDisk_2_DeleteWithInstance($dataDisk_2_DeleteWithInstance)
 * @method string getDataDisk_2_DeleteWithInstance()
 * @method $this setDataDisk_3_DeleteWithInstance($dataDisk_3_DeleteWithInstance)
 * @method string getDataDisk_3_DeleteWithInstance()
 * @method $this setDataDisk_4_DeleteWithInstance($dataDisk_4_DeleteWithInstance)
 * @method string getDataDisk_4_DeleteWithInstance()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class CreateScalingConfiguration extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setScheduledAction_1($scheduledAction_1)
 * @method string getScheduledAction_1()
 * @method $this setScheduledAction_2($scheduledAction_2)
 * @method string getScheduledAction_2()
 * @method $this setScheduledAction_3($scheduledAction_3)
 * @method string getScheduledAction_3()
 * @method $this setScheduledAction_4($scheduledAction_4)
 * @method string getScheduledAction_4()
 * @method $this setScheduledAction_5($scheduledAction_5)
 * @method string getScheduledAction_5()
 * @method $this setScheduledAction_6($scheduledAction_6)
 * @method string getScheduledAction_6()
 * @method $this setScheduledAction_7($scheduledAction_7)
 * @method string getScheduledAction_7()
 * @method $this setScheduledAction_8($scheduledAction_8)
 * @method string getScheduledAction_8()
 * @method $this setScheduledAction_9($scheduledAction_9)
 * @method string getScheduledAction_9()
 * @method $this setScheduledAction_10($scheduledAction_10)
 * @method string getScheduledAction_10()
 * @method $this setScheduledAction_11($scheduledAction_11)
 * @method string getScheduledAction_11()
 * @method $this setScheduledAction_12($scheduledAction_12)
 * @method string getScheduledAction_12()
 * @method $this setScheduledAction_13($scheduledAction_13)
 * @method string getScheduledAction_13()
 * @method $this setScheduledAction_14($scheduledAction_14)
 * @method string getScheduledAction_14()
 * @method $this setScheduledAction_15($scheduledAction_15)
 * @method string getScheduledAction_15()
 * @method $this setScheduledAction_16($scheduledAction_16)
 * @method string getScheduledAction_16()
 * @method $this setScheduledAction_17($scheduledAction_17)
 * @method string getScheduledAction_17()
 * @method $this setScheduledAction_18($scheduledAction_18)
 * @method string getScheduledAction_18()
 * @method $this setScheduledAction_19($scheduledAction_19)
 * @method string getScheduledAction_19()
 * @method $this setScheduledAction_20($scheduledAction_20)
 * @method string getScheduledAction_20()
 * @method $this setScheduledTaskId_1($scheduledTaskId_1)
 * @method string getScheduledTaskId_1()
 * @method $this setScheduledTaskId_2($scheduledTaskId_2)
 * @method string getScheduledTaskId_2()
 * @method $this setScheduledTaskId_3($scheduledTaskId_3)
 * @method string getScheduledTaskId_3()
 * @method $this setScheduledTaskId_4($scheduledTaskId_4)
 * @method string getScheduledTaskId_4()
 * @method $this setScheduledTaskId_5($scheduledTaskId_5)
 * @method string getScheduledTaskId_5()
 * @method $this setScheduledTaskId_6($scheduledTaskId_6)
 * @method string getScheduledTaskId_6()
 * @method $this setScheduledTaskId_7($scheduledTaskId_7)
 * @method string getScheduledTaskId_7()
 * @method $this setScheduledTaskId_8($scheduledTaskId_8)
 * @method string getScheduledTaskId_8()
 * @method $this setScheduledTaskId_9($scheduledTaskId_9)
 * @method string getScheduledTaskId_9()
 * @method $this setScheduledTaskId_10($scheduledTaskId_10)
 * @method string getScheduledTaskId_10()
 * @method $this setScheduledTaskId_11($scheduledTaskId_11)
 * @method string getScheduledTaskId_11()
 * @method $this setScheduledTaskId_12($scheduledTaskId_12)
 * @method string getScheduledTaskId_12()
 * @method $this setScheduledTaskId_13($scheduledTaskId_13)
 * @method string getScheduledTaskId_13()
 * @method $this setScheduledTaskId_14($scheduledTaskId_14)
 * @method string getScheduledTaskId_14()
 * @method $this setScheduledTaskId_15($scheduledTaskId_15)
 * @method string getScheduledTaskId_15()
 * @method $this setScheduledTaskId_16($scheduledTaskId_16)
 * @method string getScheduledTaskId_16()
 * @method $this setScheduledTaskId_17($scheduledTaskId_17)
 * @method string getScheduledTaskId_17()
 * @method $this setScheduledTaskId_18($scheduledTaskId_18)
 * @method string getScheduledTaskId_18()
 * @method $this setScheduledTaskId_19($scheduledTaskId_19)
 * @method string getScheduledTaskId_19()
 * @method $this setScheduledTaskId_20($scheduledTaskId_20)
 * @method string getScheduledTaskId_20()
 * @method $this setScheduledTaskName_1($scheduledTaskName_1)
 * @method string getScheduledTaskName_1()
 * @method $this setScheduledTaskName_2($scheduledTaskName_2)
 * @method string getScheduledTaskName_2()
 * @method $this setScheduledTaskName_3($scheduledTaskName_3)
 * @method string getScheduledTaskName_3()
 * @method $this setScheduledTaskName_4($scheduledTaskName_4)
 * @method string getScheduledTaskName_4()
 * @method $this setScheduledTaskName_5($scheduledTaskName_5)
 * @method string getScheduledTaskName_5()
 * @method $this setScheduledTaskName_6($scheduledTaskName_6)
 * @method string getScheduledTaskName_6()
 * @method $this setScheduledTaskName_7($scheduledTaskName_7)
 * @method string getScheduledTaskName_7()
 * @method $this setScheduledTaskName_8($scheduledTaskName_8)
 * @method string getScheduledTaskName_8()
 * @method $this setScheduledTaskName_9($scheduledTaskName_9)
 * @method string getScheduledTaskName_9()
 * @method $this setScheduledTaskName_10($scheduledTaskName_10)
 * @method string getScheduledTaskName_10()
 * @method $this setScheduledTaskName_11($scheduledTaskName_11)
 * @method string getScheduledTaskName_11()
 * @method $this setScheduledTaskName_12($scheduledTaskName_12)
 * @method string getScheduledTaskName_12()
 * @method $this setScheduledTaskName_13($scheduledTaskName_13)
 * @method string getScheduledTaskName_13()
 * @method $this setScheduledTaskName_14($scheduledTaskName_14)
 * @method string getScheduledTaskName_14()
 * @method $this setScheduledTaskName_15($scheduledTaskName_15)
 * @method string getScheduledTaskName_15()
 * @method $this setScheduledTaskName_16($scheduledTaskName_16)
 * @method string getScheduledTaskName_16()
 * @method $this setScheduledTaskName_17($scheduledTaskName_17)
 * @method string getScheduledTaskName_17()
 * @method $this setScheduledTaskName_18($scheduledTaskName_18)
 * @method string getScheduledTaskName_18()
 * @method $this setScheduledTaskName_19($scheduledTaskName_19)
 * @method string getScheduledTaskName_19()
 * @method $this setScheduledTaskName_20($scheduledTaskName_20)
 * @method string getScheduledTaskName_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeScheduledTasks extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setScheduledTaskName($scheduledTaskName)
 * @method string getScheduledTaskName()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setScheduledAction($scheduledAction)
 * @method string getScheduledAction()
 * @method $this setRecurrenceEndTime($recurrenceEndTime)
 * @method string getRecurrenceEndTime()
 * @method $this setLaunchTime($launchTime)
 * @method string getLaunchTime()
 * @method $this setRecurrenceType($recurrenceType)
 * @method string getRecurrenceType()
 * @method $this setRecurrenceValue($recurrenceValue)
 * @method string getRecurrenceValue()
 * @method $this setTaskEnabled($taskEnabled)
 * @method bool getTaskEnabled()
 * @method $this setLaunchExpirationTime($launchExpirationTime)
 * @method int getLaunchExpirationTime()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class CreateScheduledTask extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setInstanceId_1($instanceId_1)
 * @method string getInstanceId_1()
 * @method $this setInstanceId_2($instanceId_2)
 * @method string getInstanceId_2()
 * @method $this setInstanceId_3($instanceId_3)
 * @method string getInstanceId_3()
 * @method $this setInstanceId_4($instanceId_4)
 * @method string getInstanceId_4()
 * @method $this setInstanceId_5($instanceId_5)
 * @method string getInstanceId_5()
 * @method $this setInstanceId_6($instanceId_6)
 * @method string getInstanceId_6()
 * @method $this setInstanceId_7($instanceId_7)
 * @method string getInstanceId_7()
 * @method $this setInstanceId_8($instanceId_8)
 * @method string getInstanceId_8()
 * @method $this setInstanceId_9($instanceId_9)
 * @method string getInstanceId_9()
 * @method $this setInstanceId_10($instanceId_10)
 * @method string getInstanceId_10()
 * @method $this setInstanceId_11($instanceId_11)
 * @method string getInstanceId_11()
 * @method $this setInstanceId_12($instanceId_12)
 * @method string getInstanceId_12()
 * @method $this setInstanceId_13($instanceId_13)
 * @method string getInstanceId_13()
 * @method $this setInstanceId_14($instanceId_14)
 * @method string getInstanceId_14()
 * @method $this setInstanceId_15($instanceId_15)
 * @method string getInstanceId_15()
 * @method $this setInstanceId_16($instanceId_16)
 * @method string getInstanceId_16()
 * @method $this setInstanceId_17($instanceId_17)
 * @method string getInstanceId_17()
 * @method $this setInstanceId_18($instanceId_18)
 * @method string getInstanceId_18()
 * @method $this setInstanceId_19($instanceId_19)
 * @method string getInstanceId_19()
 * @method $this setInstanceId_20($instanceId_20)
 * @method string getInstanceId_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DetachInstances extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setScalingRuleId_1($scalingRuleId_1)
 * @method string getScalingRuleId_1()
 * @method $this setScalingRuleId_2($scalingRuleId_2)
 * @method string getScalingRuleId_2()
 * @method $this setScalingRuleId_3($scalingRuleId_3)
 * @method string getScalingRuleId_3()
 * @method $this setScalingRuleId_4($scalingRuleId_4)
 * @method string getScalingRuleId_4()
 * @method $this setScalingRuleId_5($scalingRuleId_5)
 * @method string getScalingRuleId_5()
 * @method $this setScalingRuleId_6($scalingRuleId_6)
 * @method string getScalingRuleId_6()
 * @method $this setScalingRuleId_7($scalingRuleId_7)
 * @method string getScalingRuleId_7()
 * @method $this setScalingRuleId_8($scalingRuleId_8)
 * @method string getScalingRuleId_8()
 * @method $this setScalingRuleId_9($scalingRuleId_9)
 * @method string getScalingRuleId_9()
 * @method $this setScalingRuleId_10($scalingRuleId_10)
 * @method string getScalingRuleId_10()
 * @method $this setScalingRuleName_1($scalingRuleName_1)
 * @method string getScalingRuleName_1()
 * @method $this setScalingRuleName_2($scalingRuleName_2)
 * @method string getScalingRuleName_2()
 * @method $this setScalingRuleName_3($scalingRuleName_3)
 * @method string getScalingRuleName_3()
 * @method $this setScalingRuleName_4($scalingRuleName_4)
 * @method string getScalingRuleName_4()
 * @method $this setScalingRuleName_5($scalingRuleName_5)
 * @method string getScalingRuleName_5()
 * @method $this setScalingRuleName_6($scalingRuleName_6)
 * @method string getScalingRuleName_6()
 * @method $this setScalingRuleName_7($scalingRuleName_7)
 * @method string getScalingRuleName_7()
 * @method $this setScalingRuleName_8($scalingRuleName_8)
 * @method string getScalingRuleName_8()
 * @method $this setScalingRuleName_9($scalingRuleName_9)
 * @method string getScalingRuleName_9()
 * @method $this setScalingRuleName_10($scalingRuleName_10)
 * @method string getScalingRuleName_10()
 * @method $this setScalingRuleAri_1($scalingRuleAri_1)
 * @method string getScalingRuleAri_1()
 * @method $this setScalingRuleAri_2($scalingRuleAri_2)
 * @method string getScalingRuleAri_2()
 * @method $this setScalingRuleAri_3($scalingRuleAri_3)
 * @method string getScalingRuleAri_3()
 * @method $this setScalingRuleAri_4($scalingRuleAri_4)
 * @method string getScalingRuleAri_4()
 * @method $this setScalingRuleAri_5($scalingRuleAri_5)
 * @method string getScalingRuleAri_5()
 * @method $this setScalingRuleAri_6($scalingRuleAri_6)
 * @method string getScalingRuleAri_6()
 * @method $this setScalingRuleAri_7($scalingRuleAri_7)
 * @method string getScalingRuleAri_7()
 * @method $this setScalingRuleAri_8($scalingRuleAri_8)
 * @method string getScalingRuleAri_8()
 * @method $this setScalingRuleAri_9($scalingRuleAri_9)
 * @method string getScalingRuleAri_9()
 * @method $this setScalingRuleAri_10($scalingRuleAri_10)
 * @method string getScalingRuleAri_10()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DescribeScalingRules extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingRuleId($scalingRuleId)
 * @method string getScalingRuleId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DeleteScalingRule extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DisableScalingGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setInstanceId_1($instanceId_1)
 * @method string getInstanceId_1()
 * @method $this setInstanceId_2($instanceId_2)
 * @method string getInstanceId_2()
 * @method $this setInstanceId_3($instanceId_3)
 * @method string getInstanceId_3()
 * @method $this setInstanceId_4($instanceId_4)
 * @method string getInstanceId_4()
 * @method $this setInstanceId_5($instanceId_5)
 * @method string getInstanceId_5()
 * @method $this setInstanceId_6($instanceId_6)
 * @method string getInstanceId_6()
 * @method $this setInstanceId_7($instanceId_7)
 * @method string getInstanceId_7()
 * @method $this setInstanceId_8($instanceId_8)
 * @method string getInstanceId_8()
 * @method $this setInstanceId_9($instanceId_9)
 * @method string getInstanceId_9()
 * @method $this setInstanceId_10($instanceId_10)
 * @method string getInstanceId_10()
 * @method $this setInstanceId_11($instanceId_11)
 * @method string getInstanceId_11()
 * @method $this setInstanceId_12($instanceId_12)
 * @method string getInstanceId_12()
 * @method $this setInstanceId_13($instanceId_13)
 * @method string getInstanceId_13()
 * @method $this setInstanceId_14($instanceId_14)
 * @method string getInstanceId_14()
 * @method $this setInstanceId_15($instanceId_15)
 * @method string getInstanceId_15()
 * @method $this setInstanceId_16($instanceId_16)
 * @method string getInstanceId_16()
 * @method $this setInstanceId_17($instanceId_17)
 * @method string getInstanceId_17()
 * @method $this setInstanceId_18($instanceId_18)
 * @method string getInstanceId_18()
 * @method $this setInstanceId_19($instanceId_19)
 * @method string getInstanceId_19()
 * @method $this setInstanceId_20($instanceId_20)
 * @method string getInstanceId_20()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class AttachInstances extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setScalingGroupId($scalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setForceDelete($forceDelete)
 * @method bool getForceDelete()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class DeleteScalingGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setScalingGroupName($scalingGroupName)
 * @method string getScalingGroupName()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setMinSize($minSize)
 * @method int getMinSize()
 * @method $this setMaxSize($maxSize)
 * @method int getMaxSize()
 * @method $this setDefaultCooldown($defaultCooldown)
 * @method int getDefaultCooldown()
 * @method $this setLoadBalancerIds($loadBalancerIds)
 * @method string getLoadBalancerIds()
 * @method $this setDBInstanceIds($dBInstanceIds)
 * @method string getDBInstanceIds()
 * @method $this setRemovalPolicy_1($removalPolicy_1)
 * @method string getRemovalPolicy_1()
 * @method $this setRemovalPolicy_2($removalPolicy_2)
 * @method string getRemovalPolicy_2()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setVSwitchId($vSwitchId)
 * @method string getVSwitchId()
 */
class CreateScalingGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setScalingRuleId($scalingRuleId)
 * @method string getScalingRuleId()
 * @method $this setScalingRuleName($scalingRuleName)
 * @method string getScalingRuleName()
 * @method $this setCooldown($cooldown)
 * @method int getCooldown()
 * @method $this setAdjustmentType($adjustmentType)
 * @method string getAdjustmentType()
 * @method $this setAdjustmentValue($adjustmentValue)
 * @method int getAdjustmentValue()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class ModifyScalingRule extends Request
{

}