<?php

namespace aliyun\sdk\services\Jaq20170825;

use aliyun\sdk\core\lib\Request;

/**
 * Class V20170825
 *
 * @package aliyun\sdk\services\Jaq20170825
 * @method AfsAppCheck AfsAppCheck()
 * @method ActivityPrevention ActivityPrevention()
 * @method SpamRegisterPrevention SpamRegisterPrevention()
 * @method AfsCheck AfsCheck()
 * @method BbsPrevention BbsPrevention()
 * @method CheckAccountAndPasswordRisk CheckAccountAndPasswordRisk()
 * @method LoginPrevention LoginPrevention()
 * @method GetAntiCheatExcelResult GetAntiCheatExcelResult()
 * @method MessagePrevention MessagePrevention()
 * @method OtherPrevention OtherPrevention()
 */
class V20170825
{
}

/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setSession($session)
 * @method string getSession()
 */
class AfsAppCheck extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setIp($ip)
 * @method string getIp()
 * @method $this setProtocolVersion($protocolVersion)
 * @method string getProtocolVersion()
 * @method $this setSource($source)
 * @method int getSource()
 * @method $this setActivityDescription($activityDescription)
 * @method string getActivityDescription()
 * @method $this setActivityId($activityId)
 * @method string getActivityId()
 * @method $this setPrize($prize)
 * @method string getPrize()
 * @method $this setPrizeType($prizeType)
 * @method int getPrizeType()
 * @method $this setPhoneNumber($phoneNumber)
 * @method string getPhoneNumber()
 * @method $this setEmail($email)
 * @method string getEmail()
 * @method $this setUserId($userId)
 * @method string getUserId()
 * @method $this setIdType($idType)
 * @method int getIdType()
 * @method $this setCurrentUrl($currentUrl)
 * @method string getCurrentUrl()
 * @method $this setAgent($agent)
 * @method string getAgent()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setSessionId($sessionId)
 * @method string getSessionId()
 * @method $this setMacAddress($macAddress)
 * @method string getMacAddress()
 * @method $this setReferer($referer)
 * @method string getReferer()
 * @method $this setUserName($userName)
 * @method string getUserName()
 * @method $this setCompanyName($companyName)
 * @method string getCompanyName()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setIDNumber($iDNumber)
 * @method string getIDNumber()
 * @method $this setBankCardNumber($bankCardNumber)
 * @method string getBankCardNumber()
 * @method $this setRegisterIp($registerIp)
 * @method string getRegisterIp()
 * @method $this setRegisterDate($registerDate)
 * @method int getRegisterDate()
 * @method $this setExtendData($extendData)
 * @method string getExtendData()
 * @method $this setJsToken($jsToken)
 * @method string getJsToken()
 * @method $this setSDKToken($sDKToken)
 * @method string getSDKToken()
 */
class ActivityPrevention extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setIp($ip)
 * @method string getIp()
 * @method $this setProtocolVersion($protocolVersion)
 * @method string getProtocolVersion()
 * @method $this setSource($source)
 * @method int getSource()
 * @method $this setPhoneNumber($phoneNumber)
 * @method string getPhoneNumber()
 * @method $this setEmail($email)
 * @method string getEmail()
 * @method $this setUserId($userId)
 * @method string getUserId()
 * @method $this setIdType($idType)
 * @method int getIdType()
 * @method $this setCurrentUrl($currentUrl)
 * @method string getCurrentUrl()
 * @method $this setAgent($agent)
 * @method string getAgent()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setSessionId($sessionId)
 * @method string getSessionId()
 * @method $this setMacAddress($macAddress)
 * @method string getMacAddress()
 * @method $this setReferer($referer)
 * @method string getReferer()
 * @method $this setNickName($nickName)
 * @method string getNickName()
 * @method $this setCompanyName($companyName)
 * @method string getCompanyName()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setIDNumber($iDNumber)
 * @method string getIDNumber()
 * @method $this setBankCardNumber($bankCardNumber)
 * @method string getBankCardNumber()
 * @method $this setJsToken($jsToken)
 * @method string getJsToken()
 * @method $this setSDKToken($sDKToken)
 * @method string getSDKToken()
 * @method $this setExtendData($extendData)
 * @method string getExtendData()
 */
class SpamRegisterPrevention extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setSession($session)
 * @method string getSession()
 * @method $this setToken($token)
 * @method string getToken()
 * @method $this setSig($sig)
 * @method string getSig()
 * @method $this setPlatform($platform)
 * @method int getPlatform()
 * @method $this setScene($scene)
 * @method string getScene()
 */
class AfsCheck extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setIp($ip)
 * @method string getIp()
 * @method $this setProtocolVersion($protocolVersion)
 * @method string getProtocolVersion()
 * @method $this setSource($source)
 * @method int getSource()
 * @method $this setPhoneNumber($phoneNumber)
 * @method string getPhoneNumber()
 * @method $this setEmail($email)
 * @method string getEmail()
 * @method $this setUserId($userId)
 * @method string getUserId()
 * @method $this setIdType($idType)
 * @method int getIdType()
 * @method $this setCurrentUrl($currentUrl)
 * @method string getCurrentUrl()
 * @method $this setAgent($agent)
 * @method string getAgent()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setSessionId($sessionId)
 * @method string getSessionId()
 * @method $this setMacAddress($macAddress)
 * @method string getMacAddress()
 * @method $this setReferer($referer)
 * @method string getReferer()
 * @method $this setNickName($nickName)
 * @method string getNickName()
 * @method $this setCompanyName($companyName)
 * @method string getCompanyName()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setJsToken($jsToken)
 * @method string getJsToken()
 * @method $this setSDKToken($sDKToken)
 * @method string getSDKToken()
 * @method $this setExtendData($extendData)
 * @method string getExtendData()
 */
class BbsPrevention extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setAccountName($accountName)
 * @method string getAccountName()
 * @method $this setPasswordHash($passwordHash)
 * @method string getPasswordHash()
 */
class CheckAccountAndPasswordRisk extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setIp($ip)
 * @method string getIp()
 * @method $this setProtocolVersion($protocolVersion)
 * @method string getProtocolVersion()
 * @method $this setSource($source)
 * @method int getSource()
 * @method $this setPhoneNumber($phoneNumber)
 * @method string getPhoneNumber()
 * @method $this setEmail($email)
 * @method string getEmail()
 * @method $this setUserId($userId)
 * @method string getUserId()
 * @method $this setIdType($idType)
 * @method int getIdType()
 * @method $this setCurrentUrl($currentUrl)
 * @method string getCurrentUrl()
 * @method $this setAgent($agent)
 * @method string getAgent()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setSessionId($sessionId)
 * @method string getSessionId()
 * @method $this setMacAddress($macAddress)
 * @method string getMacAddress()
 * @method $this setReferer($referer)
 * @method string getReferer()
 * @method $this setUserName($userName)
 * @method string getUserName()
 * @method $this setCompanyName($companyName)
 * @method string getCompanyName()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setIDNumber($iDNumber)
 * @method string getIDNumber()
 * @method $this setBankCardNumber($bankCardNumber)
 * @method string getBankCardNumber()
 * @method $this setRegisterIp($registerIp)
 * @method string getRegisterIp()
 * @method $this setRegisterDate($registerDate)
 * @method int getRegisterDate()
 * @method $this setAccountExist($accountExist)
 * @method int getAccountExist()
 * @method $this setExtendData($extendData)
 * @method string getExtendData()
 * @method $this setJsToken($jsToken)
 * @method string getJsToken()
 * @method $this setSDKToken($sDKToken)
 * @method string getSDKToken()
 * @method $this setPasswordHash($passwordHash)
 * @method string getPasswordHash()
 * @method $this setLoginType($loginType)
 * @method int getLoginType()
 * @method $this setPasswordCorrect($passwordCorrect)
 * @method int getPasswordCorrect()
 */
class LoginPrevention extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setPackages($packages)
 * @method array getPackages()
 * @method $this setStartDay($startDay)
 * @method string getStartDay()
 * @method $this setEndDay($endDay)
 * @method string getEndDay()
 */
class GetAntiCheatExcelResult extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setIp($ip)
 * @method string getIp()
 * @method $this setProtocolVersion($protocolVersion)
 * @method string getProtocolVersion()
 * @method $this setSource($source)
 * @method int getSource()
 * @method $this setPhoneNumber($phoneNumber)
 * @method string getPhoneNumber()
 * @method $this setEmail($email)
 * @method string getEmail()
 * @method $this setUserId($userId)
 * @method string getUserId()
 * @method $this setIdType($idType)
 * @method int getIdType()
 * @method $this setCurrentUrl($currentUrl)
 * @method string getCurrentUrl()
 * @method $this setAgent($agent)
 * @method string getAgent()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setSessionId($sessionId)
 * @method string getSessionId()
 * @method $this setMacAddress($macAddress)
 * @method string getMacAddress()
 * @method $this setReferer($referer)
 * @method string getReferer()
 * @method $this setUserName($userName)
 * @method string getUserName()
 * @method $this setCompanyName($companyName)
 * @method string getCompanyName()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setIDNumber($iDNumber)
 * @method string getIDNumber()
 * @method $this setBankCardNumber($bankCardNumber)
 * @method string getBankCardNumber()
 * @method $this setRegisterIp($registerIp)
 * @method string getRegisterIp()
 * @method $this setRegisterDate($registerDate)
 * @method int getRegisterDate()
 * @method $this setLoginIp($loginIp)
 * @method string getLoginIp()
 * @method $this setLoginDate($loginDate)
 * @method int getLoginDate()
 * @method $this setExtendData($extendData)
 * @method string getExtendData()
 * @method $this setPasswordHash($passwordHash)
 * @method string getPasswordHash()
 * @method $this setJsToken($jsToken)
 * @method string getJsToken()
 * @method $this setSDKToken($sDKToken)
 * @method string getSDKToken()
 */
class MessagePrevention extends Request
{
}/**
 * @method $this setCallerName($callerName)
 * @method string getCallerName()
 * @method $this setIp($ip)
 * @method string getIp()
 * @method $this setProtocolVersion($protocolVersion)
 * @method string getProtocolVersion()
 * @method $this setSource($source)
 * @method int getSource()
 * @method $this setPhoneNumber($phoneNumber)
 * @method string getPhoneNumber()
 * @method $this setEmail($email)
 * @method string getEmail()
 * @method $this setUserId($userId)
 * @method string getUserId()
 * @method $this setIdType($idType)
 * @method int getIdType()
 * @method $this setCurrentUrl($currentUrl)
 * @method string getCurrentUrl()
 * @method $this setAgent($agent)
 * @method string getAgent()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setSessionId($sessionId)
 * @method string getSessionId()
 * @method $this setMacAddress($macAddress)
 * @method string getMacAddress()
 * @method $this setReferer($referer)
 * @method string getReferer()
 * @method $this setUserName($userName)
 * @method string getUserName()
 * @method $this setCompanyName($companyName)
 * @method string getCompanyName()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setIDNumber($iDNumber)
 * @method string getIDNumber()
 * @method $this setBankCardNumber($bankCardNumber)
 * @method string getBankCardNumber()
 * @method $this setRegisterIp($registerIp)
 * @method string getRegisterIp()
 * @method $this setRegisterDate($registerDate)
 * @method int getRegisterDate()
 * @method $this setLoginIp($loginIp)
 * @method string getLoginIp()
 * @method $this setLoginDate($loginDate)
 * @method int getLoginDate()
 * @method $this setExtendData($extendData)
 * @method string getExtendData()
 * @method $this setPasswordHash($passwordHash)
 * @method string getPasswordHash()
 * @method $this setJsToken($jsToken)
 * @method string getJsToken()
 * @method $this setSDKToken($sDKToken)
 * @method string getSDKToken()
 */
class OtherPrevention extends Request
{
}
