<?php

namespace aliyun\sdk\services\Slb20130221;

use aliyun\sdk\core\lib\Request;

/**
 * Class V20130221
 *
 * @package aliyun\sdk\services\Slb20130221
 * @method AddBackendServers AddBackendServers()
 * @method RemoveBackendServers RemoveBackendServers()
 * @method CreateLoadBalancerHTTPListener CreateLoadBalancerHTTPListener()
 * @method DescribeLoadBalancerTCPListenerAttribute DescribeLoadBalancerTCPListenerAttribute()
 * @method DescribeLoadBalancerAttribute DescribeLoadBalancerAttribute()
 * @method DescribeRegions DescribeRegions()
 * @method CreateLoadBalancerTCPListener CreateLoadBalancerTCPListener()
 * @method CreateLoadBalancer CreateLoadBalancer()
 * @method SetLoadBalancerListenerStatus SetLoadBalancerListenerStatus()
 * @method DeleteLoadBalancer DeleteLoadBalancer()
 * @method SetLoadBalancerTCPListenerAttribute SetLoadBalancerTCPListenerAttribute()
 * @method SetLoadBalancerStatus SetLoadBalancerStatus()
 * @method DescribeLoadBalancerHTTPListenerAttribute DescribeLoadBalancerHTTPListenerAttribute()
 * @method SetLoadBalancerName SetLoadBalancerName()
 * @method DescribeLoadBalancers DescribeLoadBalancers()
 * @method SetLoadBalancerHTTPListenerAttribute SetLoadBalancerHTTPListenerAttribute()
 * @method DescribeBackendServers DescribeBackendServers()
 * @method SetLoadBanancerListenerStatus SetLoadBanancerListenerStatus()
 * @method DeleteLoadBalancerListener DeleteLoadBalancerListener()
 */
class V20130221
{
}

/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class AddBackendServers extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class RemoveBackendServers extends Request
{
}/**
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBackendServerPort($backendServerPort)
 * @method int getBackendServerPort()
 * @method $this setListenerStatus($listenerStatus)
 * @method string getListenerStatus()
 * @method $this setXForwardedFor($xForwardedFor)
 * @method string getXForwardedFor()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($stickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($stickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($cookieTimeout)
 * @method int getCookieTimeout()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setDomain($domain)
 * @method string getDomain()
 * @method $this setURI($uRI)
 * @method string getURI()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($healthCheckTimeout)
 * @method int getHealthCheckTimeout()
 * @method $this setInterval($interval)
 * @method int getInterval()
 * @method $this setHostId($hostId)
 * @method string getHostId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class CreateLoadBalancerHTTPListener extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeLoadBalancerTCPListenerAttribute extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeLoadBalancerAttribute extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeRegions extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBackendServerPort($backendServerPort)
 * @method int getBackendServerPort()
 * @method $this setListenerStatus($listenerStatus)
 * @method string getListenerStatus()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setPersistenceTimeout($persistenceTimeout)
 * @method int getPersistenceTimeout()
 * @method $this setEstablishedTimeout($establishedTimeout)
 * @method int getEstablishedTimeout()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setConnectTimeout($connectTimeout)
 * @method int getConnectTimeout()
 * @method $this setConnectPort($connectPort)
 * @method int getConnectPort()
 * @method $this setInterval($interval)
 * @method int getInterval()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setHealthCheckType($healthCheckType)
 * @method string getHealthCheckType()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setMasterSlaveServerGroupId($masterSlaveServerGroupId)
 * @method string getMasterSlaveServerGroupId()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class CreateLoadBalancerTCPListener extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setIsPublicAddress($isPublicAddress)
 * @method string getIsPublicAddress()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setLoadBalancerName($loadBalancerName)
 * @method string getLoadBalancerName()
 * @method $this setLoadBalancerMode($loadBalancerMode)
 * @method string getLoadBalancerMode()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class CreateLoadBalancer extends Request
{
}/**
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setListenerStatus($listenerStatus)
 * @method string getListenerStatus()
 * @method $this setHostId($hostId)
 * @method string getHostId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class SetLoadBalancerListenerStatus extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DeleteLoadBalancer extends Request
{
}/**
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setPersistenceTimeout($persistenceTimeout)
 * @method int getPersistenceTimeout()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setConnectTimeout($connectTimeout)
 * @method int getConnectTimeout()
 * @method $this setConnectPort($connectPort)
 * @method int getConnectPort()
 * @method $this setInterval($interval)
 * @method int getInterval()
 * @method $this setHostId($hostId)
 * @method string getHostId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class SetLoadBalancerTCPListenerAttribute extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setLoadBalancerStatus($loadBalancerStatus)
 * @method string getLoadBalancerStatus()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class SetLoadBalancerStatus extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeLoadBalancerHTTPListenerAttribute extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setLoadBalancerName($loadBalancerName)
 * @method string getLoadBalancerName()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class SetLoadBalancerName extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setServerId($serverId)
 * @method string getServerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setLoadBalancerName($loadBalancerName)
 * @method string getLoadBalancerName()
 * @method $this setServerIntranetAddress($serverIntranetAddress)
 * @method string getServerIntranetAddress()
 * @method $this setAddressType($addressType)
 * @method string getAddressType()
 * @method $this setInternetChargeType($internetChargeType)
 * @method string getInternetChargeType()
 * @method $this setVpcId($vpcId)
 * @method string getVpcId()
 * @method $this setVSwitchId($vSwitchId)
 * @method string getVSwitchId()
 * @method $this setNetworkType($networkType)
 * @method string getNetworkType()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setMasterZoneId($masterZoneId)
 * @method string getMasterZoneId()
 * @method $this setSlaveZoneId($slaveZoneId)
 * @method string getSlaveZoneId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setPayType($payType)
 * @method string getPayType()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 */
class DescribeLoadBalancers extends Request
{
}/**
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setXForwardedFor($xForwardedFor)
 * @method string getXForwardedFor()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($stickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($stickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($cookieTimeout)
 * @method int getCookieTimeout()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setDomain($domain)
 * @method string getDomain()
 * @method $this setURI($uRI)
 * @method string getURI()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($healthCheckTimeout)
 * @method int getHealthCheckTimeout()
 * @method $this setInterval($interval)
 * @method int getInterval()
 * @method $this setHostId($hostId)
 * @method string getHostId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class SetLoadBalancerHTTPListenerAttribute extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class DescribeBackendServers extends Request
{
}/**
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setListenerStatus($listenerStatus)
 * @method string getListenerStatus()
 * @method $this setHostId($hostId)
 * @method string getHostId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 */
class SetLoadBanancerListenerStatus extends Request
{
}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DeleteLoadBalancerListener extends Request
{
}
