<?php

namespace aliyun\sdk\services\Slb20140515;

use aliyun\sdk\core\lib\Request;

/**
 * Class V20140515
 *
 * @package aliyun\sdk\services\Slb20140515
 * @method AddBackendServers AddBackendServers()
 * @method SetLoadBalancerUDPListenerAttribute SetLoadBalancerUDPListenerAttribute()
 * @method SetVServerGroupAttribute SetVServerGroupAttribute()
 * @method UploadServerCertificate UploadServerCertificate()
 * @method RemoveBackendServers RemoveBackendServers()
 * @method RemoveAccessControlListEntry RemoveAccessControlListEntry()
 * @method CreateLoadBalancerHTTPListener CreateLoadBalancerHTTPListener()
 * @method AddTags AddTags()
 * @method DescribeLoadBalancerTCPListenerAttribute DescribeLoadBalancerTCPListenerAttribute()
 * @method DescribeMasterSlaveVServerGroupAttribute DescribeMasterSlaveVServerGroupAttribute()
 * @method CreateRules CreateRules()
 * @method SetRule SetRule()
 * @method RemoveTags RemoveTags()
 * @method DescribeServerCertificates DescribeServerCertificates()
 * @method DeleteServerCertificate DeleteServerCertificate()
 * @method ModifyLoadBalancerPayType ModifyLoadBalancerPayType()
 * @method DeleteMasterSlaveVServerGroup DeleteMasterSlaveVServerGroup()
 * @method StartLoadBalancerListener StartLoadBalancerListener()
 * @method DeleteAccessControlList DeleteAccessControlList()
 * @method DeleteRules DeleteRules()
 * @method DescribeListenerAccessControlAttribute DescribeListenerAccessControlAttribute()
 * @method ModifyVServerGroupBackendServers ModifyVServerGroupBackendServers()
 * @method SetDomainExtensionAttribute SetDomainExtensionAttribute()
 * @method CreateMasterSlaveVServerGroup CreateMasterSlaveVServerGroup()
 * @method CreateLoadBalancerHTTPSListener CreateLoadBalancerHTTPSListener()
 * @method SetLoadBalancerHTTPSListenerAttribute SetLoadBalancerHTTPSListenerAttribute()
 * @method DescribeCACertificates DescribeCACertificates()
 * @method CreateAccessControlList CreateAccessControlList()
 * @method StopLoadBalancerListener StopLoadBalancerListener()
 * @method SetBackendServers SetBackendServers()
 * @method DescribeLoadBalancerAttribute DescribeLoadBalancerAttribute()
 * @method SetServerCertificateName SetServerCertificateName()
 * @method DescribeHealthStatus DescribeHealthStatus()
 * @method DescribeVServerGroupAttribute DescribeVServerGroupAttribute()
 * @method DescribeLoadBalancerHTTPSListenerAttribute DescribeLoadBalancerHTTPSListenerAttribute()
 * @method SetAccessControlListAttribute SetAccessControlListAttribute()
 * @method UploadCACertificate UploadCACertificate()
 * @method AddListenerWhiteListItem AddListenerWhiteListItem()
 * @method DescribeAccessControlLists DescribeAccessControlLists()
 * @method DeleteCACertificate DeleteCACertificate()
 * @method CreateLoadBalancerUDPListener CreateLoadBalancerUDPListener()
 * @method DescribeRegions DescribeRegions()
 * @method DeleteMasterSlaveServerGroup DeleteMasterSlaveServerGroup()
 * @method DescribeLoadBalancerUDPListenerAttribute DescribeLoadBalancerUDPListenerAttribute()
 * @method ModifyLoadBalancerInstanceSpec ModifyLoadBalancerInstanceSpec()
 * @method CreateLoadBalancerTCPListener CreateLoadBalancerTCPListener()
 * @method CreateLoadBalancer CreateLoadBalancer()
 * @method AddAccessControlListEntry AddAccessControlListEntry()
 * @method DeleteLoadBalancer DeleteLoadBalancer()
 * @method SetLoadBalancerTCPListenerAttribute SetLoadBalancerTCPListenerAttribute()
 * @method SetLoadBalancerStatus SetLoadBalancerStatus()
 * @method DescribeMasterSlaveServerGroups DescribeMasterSlaveServerGroups()
 * @method DescribeLoadBalancerHTTPListenerAttribute DescribeLoadBalancerHTTPListenerAttribute()
 * @method DescribeMasterSlaveServerGroupAttribute DescribeMasterSlaveServerGroupAttribute()
 * @method SetLoadBalancerName SetLoadBalancerName()
 * @method DescribeVServerGroups DescribeVServerGroups()
 * @method SetListenerAccessControlStatus SetListenerAccessControlStatus()
 * @method RemoveListenerWhiteListItem RemoveListenerWhiteListItem()
 * @method AddVServerGroupBackendServers AddVServerGroupBackendServers()
 * @method DeleteVServerGroup DeleteVServerGroup()
 * @method DescribeLoadBalancers DescribeLoadBalancers()
 * @method CreateVServerGroup CreateVServerGroup()
 * @method DescribeRuleAttribute DescribeRuleAttribute()
 * @method DescribeTags DescribeTags()
 * @method RemoveVServerGroupBackendServers RemoveVServerGroupBackendServers()
 * @method DescribeMasterSlaveVServerGroups DescribeMasterSlaveVServerGroups()
 * @method CreateDomainExtension CreateDomainExtension()
 * @method DescribeZones DescribeZones()
 * @method DescribeRules DescribeRules()
 * @method DeleteDomainExtension DeleteDomainExtension()
 * @method DescribeDomainExtensions DescribeDomainExtensions()
 * @method ModifyLoadBalancerInternetSpec ModifyLoadBalancerInternetSpec()
 * @method SetLoadBalancerHTTPListenerAttribute SetLoadBalancerHTTPListenerAttribute()
 * @method DescribeAccessControlListAttribute DescribeAccessControlListAttribute()
 * @method DeleteLoadBalancerListener DeleteLoadBalancerListener()
 * @method CreateMasterSlaveServerGroup CreateMasterSlaveServerGroup()
 * @method SetCACertificateName SetCACertificateName()
 */
class V20140515
{
}

/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class AddBackendServers extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setPersistenceTimeout($persistenceTimeout)
 * @method int getPersistenceTimeout()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckConnectTimeout($healthCheckConnectTimeout)
 * @method int getHealthCheckConnectTimeout()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this setHealthCheckInterval($healthCheckInterval)
 * @method int getHealthCheckInterval()
 * @method $this sethealthCheckReq($healthCheckReq)
 * @method string gethealthCheckReq()
 * @method $this sethealthCheckExp($healthCheckExp)
 * @method string gethealthCheckExp()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroup($vServerGroup)
 * @method string getVServerGroup()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setMasterSlaveServerGroupId($masterSlaveServerGroupId)
 * @method string getMasterSlaveServerGroupId()
 * @method $this setMasterSlaveServerGroup($masterSlaveServerGroup)
 * @method string getMasterSlaveServerGroup()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setDescription($description)
 * @method string getDescription()
 */
class SetLoadBalancerUDPListenerAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setVServerGroupName($vServerGroupName)
 * @method string getVServerGroupName()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 */
class SetVServerGroupAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAliCloudCertificateId($aliCloudCertificateId)
 * @method string getAliCloudCertificateId()
 * @method $this setAliCloudCertificateName($aliCloudCertificateName)
 * @method string getAliCloudCertificateName()
 * @method $this setServerCertificate($serverCertificate)
 * @method string getServerCertificate()
 * @method $this setPrivateKey($privateKey)
 * @method string getPrivateKey()
 * @method $this setServerCertificateName($serverCertificateName)
 * @method string getServerCertificateName()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 */
class UploadServerCertificate extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class RemoveBackendServers extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclEntrys($aclEntrys)
 * @method string getAclEntrys()
 */
class RemoveAccessControlListEntry extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBackendServerPort($backendServerPort)
 * @method int getBackendServerPort()
 * @method $this setXForwardedFor($xForwardedFor)
 * @method string getXForwardedFor()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($stickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($stickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($cookieTimeout)
 * @method int getCookieTimeout()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($healthCheckTimeout)
 * @method int getHealthCheckTimeout()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this setHealthCheckInterval($healthCheckInterval)
 * @method int getHealthCheckInterval()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setXForwardedFor_SLBIP($xForwardedFor_SLBIP)
 * @method string getXForwardedFor_SLBIP()
 * @method $this setXForwardedFor_SLBID($xForwardedFor_SLBID)
 * @method string getXForwardedFor_SLBID()
 * @method $this setXForwardedFor_proto($xForwardedFor_proto)
 * @method string getXForwardedFor_proto()
 * @method $this setGzip($gzip)
 * @method string getGzip()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setListenerForward($listenerForward)
 * @method string getListenerForward()
 * @method $this setForwardPort($forwardPort)
 * @method int getForwardPort()
 * @method $this setIdleTimeout($idleTimeout)
 * @method int getIdleTimeout()
 * @method $this setRequestTimeout($requestTimeout)
 * @method int getRequestTimeout()
 */
class CreateLoadBalancerHTTPListener extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class AddTags extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeLoadBalancerTCPListenerAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setMasterSlaveVServerGroupId($masterSlaveVServerGroupId)
 * @method string getMasterSlaveVServerGroupId()
 */
class DescribeMasterSlaveVServerGroupAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setRuleList($ruleList)
 * @method string getRuleList()
 */
class CreateRules extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRuleId($ruleId)
 * @method string getRuleId()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setRuleName($ruleName)
 * @method string getRuleName()
 * @method $this setListenerSync($listenerSync)
 * @method string getListenerSync()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($stickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($stickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($cookieTimeout)
 * @method int getCookieTimeout()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($healthCheckTimeout)
 * @method int getHealthCheckTimeout()
 * @method $this setHealthCheckInterval($healthCheckInterval)
 * @method int getHealthCheckInterval()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 */
class SetRule extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class RemoveTags extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setServerCertificateId($serverCertificateId)
 * @method string getServerCertificateId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setTag($tag)
 * @method array getTag()
 */
class DescribeServerCertificates extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setServerCertificateId($serverCertificateId)
 * @method string getServerCertificateId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DeleteServerCertificate extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setPayType($payType)
 * @method string getPayType()
 * @method $this setPricingCycle($pricingCycle)
 * @method string getPricingCycle()
 * @method $this setDuration($duration)
 * @method int getDuration()
 * @method $this setAutoPay($autoPay)
 * @method bool getAutoPay()
 */
class ModifyLoadBalancerPayType extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setMasterSlaveVServerGroupId($masterSlaveVServerGroupId)
 * @method string getMasterSlaveVServerGroupId()
 */
class DeleteMasterSlaveVServerGroup extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class StartLoadBalancerListener extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 */
class DeleteAccessControlList extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRuleIds($ruleIds)
 * @method string getRuleIds()
 */
class DeleteRules extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeListenerAccessControlAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setOldBackendServers($oldBackendServers)
 * @method string getOldBackendServers()
 * @method $this setNewBackendServers($newBackendServers)
 * @method string getNewBackendServers()
 */
class ModifyVServerGroupBackendServers extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setDomainExtensionId($domainExtensionId)
 * @method string getDomainExtensionId()
 * @method $this setServerCertificateId($serverCertificateId)
 * @method string getServerCertificateId()
 */
class SetDomainExtensionAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setMasterSlaveVServerGroupName($masterSlaveVServerGroupName)
 * @method string getMasterSlaveVServerGroupName()
 * @method $this setMasterSlaveBackendServers($masterSlaveBackendServers)
 * @method string getMasterSlaveBackendServers()
 */
class CreateMasterSlaveVServerGroup extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBackendServerPort($backendServerPort)
 * @method int getBackendServerPort()
 * @method $this setXForwardedFor($xForwardedFor)
 * @method string getXForwardedFor()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($stickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($stickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($cookieTimeout)
 * @method int getCookieTimeout()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($healthCheckTimeout)
 * @method int getHealthCheckTimeout()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this setHealthCheckInterval($healthCheckInterval)
 * @method int getHealthCheckInterval()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setServerCertificateId($serverCertificateId)
 * @method string getServerCertificateId()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setCACertificateId($cACertificateId)
 * @method string getCACertificateId()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setXForwardedFor_SLBIP($xForwardedFor_SLBIP)
 * @method string getXForwardedFor_SLBIP()
 * @method $this setXForwardedFor_SLBID($xForwardedFor_SLBID)
 * @method string getXForwardedFor_SLBID()
 * @method $this setXForwardedFor_proto($xForwardedFor_proto)
 * @method string getXForwardedFor_proto()
 * @method $this setGzip($gzip)
 * @method string getGzip()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setDescription($description)
 * @method string getDescription()
 * @method $this setIdleTimeout($idleTimeout)
 * @method int getIdleTimeout()
 * @method $this setRequestTimeout($requestTimeout)
 * @method int getRequestTimeout()
 * @method $this setEnableHttp2($enableHttp2)
 * @method string getEnableHttp2()
 * @method $this setTLSCipherPolicy($tLSCipherPolicy)
 * @method string getTLSCipherPolicy()
 */
class CreateLoadBalancerHTTPSListener extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setXForwardedFor($xForwardedFor)
 * @method string getXForwardedFor()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($stickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($stickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($cookieTimeout)
 * @method int getCookieTimeout()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($healthCheckTimeout)
 * @method int getHealthCheckTimeout()
 * @method $this setHealthCheckInterval($healthCheckInterval)
 * @method int getHealthCheckInterval()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setServerCertificateId($serverCertificateId)
 * @method string getServerCertificateId()
 * @method $this setCACertificateId($cACertificateId)
 * @method string getCACertificateId()
 * @method $this setVServerGroup($vServerGroup)
 * @method string getVServerGroup()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setXForwardedFor_SLBIP($xForwardedFor_SLBIP)
 * @method string getXForwardedFor_SLBIP()
 * @method $this setXForwardedFor_SLBID($xForwardedFor_SLBID)
 * @method string getXForwardedFor_SLBID()
 * @method $this setXForwardedFor_proto($xForwardedFor_proto)
 * @method string getXForwardedFor_proto()
 * @method $this setGzip($gzip)
 * @method string getGzip()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setIdleTimeout($idleTimeout)
 * @method int getIdleTimeout()
 * @method $this setRequestTimeout($requestTimeout)
 * @method int getRequestTimeout()
 * @method $this setEnableHttp2($enableHttp2)
 * @method string getEnableHttp2()
 * @method $this setTLSCipherPolicy($tLSCipherPolicy)
 * @method string getTLSCipherPolicy()
 * @method $this setDescription($description)
 * @method string getDescription()
 */
class SetLoadBalancerHTTPSListenerAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setCACertificateId($cACertificateId)
 * @method string getCACertificateId()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setTag($tag)
 * @method array getTag()
 */
class DescribeCACertificates extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAclName($aclName)
 * @method string getAclName()
 * @method $this setAddressIPVersion($addressIPVersion)
 * @method string getAddressIPVersion()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 */
class CreateAccessControlList extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class StopLoadBalancerListener extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class SetBackendServers extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setIncludeReservedData($includeReservedData)
 * @method bool getIncludeReservedData()
 */
class DescribeLoadBalancerAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setServerCertificateId($serverCertificateId)
 * @method string getServerCertificateId()
 * @method $this setServerCertificateName($serverCertificateName)
 * @method string getServerCertificateName()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class SetServerCertificateName extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class DescribeHealthStatus extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 */
class DescribeVServerGroupAttribute extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeLoadBalancerHTTPSListenerAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclName($aclName)
 * @method string getAclName()
 */
class SetAccessControlListAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setCACertificate($cACertificate)
 * @method string getCACertificate()
 * @method $this setCACertificateName($cACertificateName)
 * @method string getCACertificateName()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 */
class UploadCACertificate extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setSourceItems($sourceItems)
 * @method string getSourceItems()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class AddListenerWhiteListItem extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAclName($aclName)
 * @method string getAclName()
 * @method $this setAddressIPVersion($addressIPVersion)
 * @method string getAddressIPVersion()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setTag($tag)
 * @method array getTag()
 */
class DescribeAccessControlLists extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setCACertificateId($cACertificateId)
 * @method string getCACertificateId()
 */
class DeleteCACertificate extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBackendServerPort($backendServerPort)
 * @method int getBackendServerPort()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setPersistenceTimeout($persistenceTimeout)
 * @method int getPersistenceTimeout()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckConnectTimeout($healthCheckConnectTimeout)
 * @method int getHealthCheckConnectTimeout()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this sethealthCheckInterval($healthCheckInterval)
 * @method int gethealthCheckInterval()
 * @method $this sethealthCheckReq($healthCheckReq)
 * @method string gethealthCheckReq()
 * @method $this sethealthCheckExp($healthCheckExp)
 * @method string gethealthCheckExp()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setMasterSlaveServerGroupId($masterSlaveServerGroupId)
 * @method string getMasterSlaveServerGroupId()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setDescription($description)
 * @method string getDescription()
 */
class CreateLoadBalancerUDPListener extends Request
{

}/**
 * @method $this setAcceptLanguage($acceptLanguage)
 * @method string getAcceptLanguage()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeRegions extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setMasterSlaveServerGroupId($masterSlaveServerGroupId)
 * @method string getMasterSlaveServerGroupId()
 */
class DeleteMasterSlaveServerGroup extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeLoadBalancerUDPListenerAttribute extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerSpec($loadBalancerSpec)
 * @method string getLoadBalancerSpec()
 * @method $this setAutoPay($autoPay)
 * @method bool getAutoPay()
 */
class ModifyLoadBalancerInstanceSpec extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBackendServerPort($backendServerPort)
 * @method int getBackendServerPort()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setPersistenceTimeout($persistenceTimeout)
 * @method int getPersistenceTimeout()
 * @method $this setEstablishedTimeout($establishedTimeout)
 * @method int getEstablishedTimeout()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckConnectTimeout($healthCheckConnectTimeout)
 * @method int getHealthCheckConnectTimeout()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this sethealthCheckInterval($healthCheckInterval)
 * @method int gethealthCheckInterval()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setHealthCheckType($healthCheckType)
 * @method string getHealthCheckType()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setMasterSlaveServerGroupId($masterSlaveServerGroupId)
 * @method string getMasterSlaveServerGroupId()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setDescription($description)
 * @method string getDescription()
 */
class CreateLoadBalancerTCPListener extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAddressType($addressType)
 * @method string getAddressType()
 * @method $this setInternetChargeType($internetChargeType)
 * @method string getInternetChargeType()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setClientToken($clientToken)
 * @method string getClientToken()
 * @method $this setLoadBalancerName($loadBalancerName)
 * @method string getLoadBalancerName()
 * @method $this setVpcId($vpcId)
 * @method string getVpcId()
 * @method $this setVSwitchId($vSwitchId)
 * @method string getVSwitchId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setMasterZoneId($masterZoneId)
 * @method string getMasterZoneId()
 * @method $this setSlaveZoneId($slaveZoneId)
 * @method string getSlaveZoneId()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setEnableVpcVipFlow($enableVpcVipFlow)
 * @method string getEnableVpcVipFlow()
 * @method $this setLoadBalancerSpec($loadBalancerSpec)
 * @method string getLoadBalancerSpec()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setPayType($payType)
 * @method string getPayType()
 * @method $this setPricingCycle($pricingCycle)
 * @method string getPricingCycle()
 * @method $this setDuration($duration)
 * @method int getDuration()
 * @method $this setAutoPay($autoPay)
 * @method bool getAutoPay()
 * @method $this setAddressIPVersion($addressIPVersion)
 * @method string getAddressIPVersion()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setRatio($ratio)
 * @method int getRatio()
 */
class CreateLoadBalancer extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclEntrys($aclEntrys)
 * @method string getAclEntrys()
 */
class AddAccessControlListEntry extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DeleteLoadBalancer extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setPersistenceTimeout($persistenceTimeout)
 * @method int getPersistenceTimeout()
 * @method $this setEstablishedTimeout($establishedTimeout)
 * @method int getEstablishedTimeout()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckConnectTimeout($healthCheckConnectTimeout)
 * @method int getHealthCheckConnectTimeout()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this setHealthCheckInterval($healthCheckInterval)
 * @method int getHealthCheckInterval()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setHealthCheckType($healthCheckType)
 * @method string getHealthCheckType()
 * @method $this setSynProxy($synProxy)
 * @method string getSynProxy()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroup($vServerGroup)
 * @method string getVServerGroup()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setMasterSlaveServerGroupId($masterSlaveServerGroupId)
 * @method string getMasterSlaveServerGroupId()
 * @method $this setMasterSlaveServerGroup($masterSlaveServerGroup)
 * @method string getMasterSlaveServerGroup()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setDescription($description)
 * @method string getDescription()
 */
class SetLoadBalancerTCPListenerAttribute extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setLoadBalancerStatus($loadBalancerStatus)
 * @method string getLoadBalancerStatus()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class SetLoadBalancerStatus extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setIncludeListener($includeListener)
 * @method bool getIncludeListener()
 */
class DescribeMasterSlaveServerGroups extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DescribeLoadBalancerHTTPListenerAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setMasterSlaveServerGroupId($masterSlaveServerGroupId)
 * @method string getMasterSlaveServerGroupId()
 */
class DescribeMasterSlaveServerGroupAttribute extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setLoadBalancerName($loadBalancerName)
 * @method string getLoadBalancerName()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class SetLoadBalancerName extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setIncludeRule($includeRule)
 * @method bool getIncludeRule()
 * @method $this setIncludeListener($includeListener)
 * @method bool getIncludeListener()
 */
class DescribeVServerGroups extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setAccessControlStatus($accessControlStatus)
 * @method string getAccessControlStatus()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class SetListenerAccessControlStatus extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setSourceItems($sourceItems)
 * @method string getSourceItems()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class RemoveListenerWhiteListItem extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 */
class AddVServerGroupBackendServers extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 */
class DeleteVServerGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setServerId($serverId)
 * @method string getServerId()
 * @method $this setAddressIPVersion($addressIPVersion)
 * @method string getAddressIPVersion()
 * @method $this setLoadBalancerStatus($loadBalancerStatus)
 * @method string getLoadBalancerStatus()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setLoadBalancerName($loadBalancerName)
 * @method string getLoadBalancerName()
 * @method $this setServerIntranetAddress($serverIntranetAddress)
 * @method string getServerIntranetAddress()
 * @method $this setAddressType($addressType)
 * @method string getAddressType()
 * @method $this setInternetChargeType($internetChargeType)
 * @method string getInternetChargeType()
 * @method $this setVpcId($vpcId)
 * @method string getVpcId()
 * @method $this setVSwitchId($vSwitchId)
 * @method string getVSwitchId()
 * @method $this setNetworkType($networkType)
 * @method string getNetworkType()
 * @method $this setAddress($address)
 * @method string getAddress()
 * @method $this setMasterZoneId($masterZoneId)
 * @method string getMasterZoneId()
 * @method $this setSlaveZoneId($slaveZoneId)
 * @method string getSlaveZoneId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setPayType($payType)
 * @method string getPayType()
 * @method $this setResourceGroupId($resourceGroupId)
 * @method string getResourceGroupId()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setTag($tag)
 * @method array getTag()
 * @method $this setFuzzy($fuzzy)
 * @method string getFuzzy()
 */
class DescribeLoadBalancers extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setVServerGroupName($vServerGroupName)
 * @method string getVServerGroupName()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 */
class CreateVServerGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRuleId($ruleId)
 * @method string getRuleId()
 */
class DescribeRuleAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setDistinctKey($distinctKey)
 * @method bool getDistinctKey()
 * @method $this setPageSize($pageSize)
 * @method int getPageSize()
 * @method $this setPageNumber($pageNumber)
 * @method int getPageNumber()
 */
class DescribeTags extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setBackendServers($backendServers)
 * @method string getBackendServers()
 */
class RemoveVServerGroupBackendServers extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 */
class DescribeMasterSlaveVServerGroups extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setDomain($domain)
 * @method string getDomain()
 * @method $this setServerCertificateId($serverCertificateId)
 * @method string getServerCertificateId()
 */
class CreateDomainExtension extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 */
class DescribeZones extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 */
class DescribeRules extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setDomainExtensionId($domainExtensionId)
 * @method string getDomainExtensionId()
 */
class DeleteDomainExtension extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setDomainExtensionId($domainExtensionId)
 * @method string getDomainExtensionId()
 */
class DescribeDomainExtensions extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setInternetChargeType($internetChargeType)
 * @method string getInternetChargeType()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setAutoPay($autoPay)
 * @method bool getAutoPay()
 * @method $this setRatio($ratio)
 * @method int getRatio()
 */
class ModifyLoadBalancerInternetSpec extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setBandwidth($bandwidth)
 * @method int getBandwidth()
 * @method $this setXForwardedFor($xForwardedFor)
 * @method string getXForwardedFor()
 * @method $this setScheduler($scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($stickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($stickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($cookieTimeout)
 * @method int getCookieTimeout()
 * @method $this setCookie($cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($healthCheck)
 * @method string getHealthCheck()
 * @method $this setHealthCheckDomain($healthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($healthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthyThreshold($healthyThreshold)
 * @method int getHealthyThreshold()
 * @method $this setUnhealthyThreshold($unhealthyThreshold)
 * @method int getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($healthCheckTimeout)
 * @method int getHealthCheckTimeout()
 * @method $this setHealthCheckInterval($healthCheckInterval)
 * @method int getHealthCheckInterval()
 * @method $this setHealthCheckConnectPort($healthCheckConnectPort)
 * @method int getHealthCheckConnectPort()
 * @method $this setHealthCheckHttpCode($healthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setMaxConnection($maxConnection)
 * @method int getMaxConnection()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setVServerGroup($vServerGroup)
 * @method string getVServerGroup()
 * @method $this setVServerGroupId($vServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setXForwardedFor_SLBIP($xForwardedFor_SLBIP)
 * @method string getXForwardedFor_SLBIP()
 * @method $this setXForwardedFor_SLBID($xForwardedFor_SLBID)
 * @method string getXForwardedFor_SLBID()
 * @method $this setXForwardedFor_proto($xForwardedFor_proto)
 * @method string getXForwardedFor_proto()
 * @method $this setGzip($gzip)
 * @method string getGzip()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclType($aclType)
 * @method string getAclType()
 * @method $this setAclStatus($aclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($vpcIds)
 * @method string getVpcIds()
 * @method $this setIdleTimeout($idleTimeout)
 * @method int getIdleTimeout()
 * @method $this setRequestTimeout($requestTimeout)
 * @method int getRequestTimeout()
 * @method $this setDescription($description)
 * @method string getDescription()
 */
class SetLoadBalancerHTTPListenerAttribute extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setAclId($aclId)
 * @method string getAclId()
 * @method $this setAclEntryComment($aclEntryComment)
 * @method string getAclEntryComment()
 */
class DescribeAccessControlListAttribute extends Request
{

}/**
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($listenerPort)
 * @method int getListenerPort()
 * @method $this setListenerProtocol($listenerProtocol)
 * @method string getListenerProtocol()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 */
class DeleteLoadBalancerListener extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setTags($tags)
 * @method string getTags()
 * @method $this setLoadBalancerId($loadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setMasterSlaveServerGroupName($masterSlaveServerGroupName)
 * @method string getMasterSlaveServerGroupName()
 * @method $this setMasterSlaveBackendServers($masterSlaveBackendServers)
 * @method string getMasterSlaveBackendServers()
 */
class CreateMasterSlaveServerGroup extends Request
{

}/**
 * @method $this setOwnerId($ownerId)
 * @method int getOwnerId()
 * @method $this setResourceOwnerAccount($resourceOwnerAccount)
 * @method string getResourceOwnerAccount()
 * @method $this setResourceOwnerId($resourceOwnerId)
 * @method int getResourceOwnerId()
 * @method $this setOwnerAccount($ownerAccount)
 * @method string getOwnerAccount()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setRegionId($regionId)
 * @method string getRegionId()
 * @method $this setCACertificateId($cACertificateId)
 * @method string getCACertificateId()
 * @method $this setCACertificateName($cACertificateName)
 * @method string getCACertificateName()
 */
class SetCACertificateName extends Request
{

}