<?php
namespace aliyun\sdk\services\Slb\request;

use aliyun\sdk\services\Slb\SlbCommon;

/**
 * @method $this setRegionId($RegionId)
 * @method string getRegionId()
 * @method $this setLoadBalancerId($LoadBalancerId)
 * @method string getLoadBalancerId()
 * @method $this setListenerPort($ListenerPort)
 * @method integer getListenerPort()
 * @method $this setBandwidth($Bandwidth)
 * @method integer getBandwidth()
 * @method $this setXForwardedFor($XForwardedFor)
 * @method string getXForwardedFor()
 * @method $this setScheduler($Scheduler)
 * @method string getScheduler()
 * @method $this setStickySession($StickySession)
 * @method string getStickySession()
 * @method $this setStickySessionType($StickySessionType)
 * @method string getStickySessionType()
 * @method $this setCookieTimeout($CookieTimeout)
 * @method integer getCookieTimeout()
 * @method $this setCookie($Cookie)
 * @method string getCookie()
 * @method $this setHealthCheck($HealthCheck)
 * @method string getHealthCheck()
 * @method $this setHealthCheckDomain($HealthCheckDomain)
 * @method string getHealthCheckDomain()
 * @method $this setHealthCheckURI($HealthCheckURI)
 * @method string getHealthCheckURI()
 * @method $this setHealthyThreshold($HealthyThreshold)
 * @method integer getHealthyThreshold()
 * @method $this setUnhealthyThreshold($UnhealthyThreshold)
 * @method integer getUnhealthyThreshold()
 * @method $this setHealthCheckTimeout($HealthCheckTimeout)
 * @method integer getHealthCheckTimeout()
 * @method $this setHealthCheckInterval($HealthCheckInterval)
 * @method integer getHealthCheckInterval()
 * @method $this setHealthCheckConnectPort($HealthCheckConnectPort)
 * @method integer getHealthCheckConnectPort()
 * @method $this setHealthCheckHttpCode($HealthCheckHttpCode)
 * @method string getHealthCheckHttpCode()
 * @method $this setMaxConnection($MaxConnection)
 * @method integer getMaxConnection()
 * @method $this setaccess_key_id($access_key_id)
 * @method string getaccess_key_id()
 * @method $this setVServerGroup($VServerGroup)
 * @method string getVServerGroup()
 * @method $this setVServerGroupId($VServerGroupId)
 * @method string getVServerGroupId()
 * @method $this setTags($Tags)
 * @method string getTags()
 * @method $this setXForwardedFor_SLBIP($XForwardedFor_SLBIP)
 * @method string getXForwardedFor_SLBIP()
 * @method $this setXForwardedFor_SLBID($XForwardedFor_SLBID)
 * @method string getXForwardedFor_SLBID()
 * @method $this setXForwardedFor_proto($XForwardedFor_proto)
 * @method string getXForwardedFor_proto()
 * @method $this setGzip($Gzip)
 * @method string getGzip()
 * @method $this setAclId($AclId)
 * @method string getAclId()
 * @method $this setAclType($AclType)
 * @method string getAclType()
 * @method $this setAclStatus($AclStatus)
 * @method string getAclStatus()
 * @method $this setVpcIds($VpcIds)
 * @method string getVpcIds()
 * @method $this setIdleTimeout($IdleTimeout)
 * @method integer getIdleTimeout()
 * @method $this setRequestTimeout($RequestTimeout)
 * @method integer getRequestTimeout()
 * @method $this setDescription($Description)
 * @method string getDescription()
 */
final class SetLoadBalancerHTTPListenerAttribute extends SlbCommon
{
    public $action = 'SetLoadBalancerHTTPListenerAttribute';
}
