<?php
namespace aliyun\sdk\services\Ess\request;

use aliyun\sdk\services\Ess\EssCommon;

/**
 * @method $this setAccessKeyId($AccessKeyId)
 * @method string getAccessKeyId()
 * @method $this setScalingGroupId($ScalingGroupId)
 * @method string getScalingGroupId()
 * @method $this setInstanceId_1($InstanceId_1)
 * @method string getInstanceId_1()
 * @method $this setInstanceId_2($InstanceId_2)
 * @method string getInstanceId_2()
 * @method $this setInstanceId_3($InstanceId_3)
 * @method string getInstanceId_3()
 * @method $this setInstanceId_4($InstanceId_4)
 * @method string getInstanceId_4()
 * @method $this setInstanceId_5($InstanceId_5)
 * @method string getInstanceId_5()
 * @method $this setInstanceId_6($InstanceId_6)
 * @method string getInstanceId_6()
 * @method $this setInstanceId_7($InstanceId_7)
 * @method string getInstanceId_7()
 * @method $this setInstanceId_8($InstanceId_8)
 * @method string getInstanceId_8()
 * @method $this setInstanceId_9($InstanceId_9)
 * @method string getInstanceId_9()
 * @method $this setInstanceId_10($InstanceId_10)
 * @method string getInstanceId_10()
 * @method $this setInstanceId_11($InstanceId_11)
 * @method string getInstanceId_11()
 * @method $this setInstanceId_12($InstanceId_12)
 * @method string getInstanceId_12()
 * @method $this setInstanceId_13($InstanceId_13)
 * @method string getInstanceId_13()
 * @method $this setInstanceId_14($InstanceId_14)
 * @method string getInstanceId_14()
 * @method $this setInstanceId_15($InstanceId_15)
 * @method string getInstanceId_15()
 * @method $this setInstanceId_16($InstanceId_16)
 * @method string getInstanceId_16()
 * @method $this setInstanceId_17($InstanceId_17)
 * @method string getInstanceId_17()
 * @method $this setInstanceId_18($InstanceId_18)
 * @method string getInstanceId_18()
 * @method $this setInstanceId_19($InstanceId_19)
 * @method string getInstanceId_19()
 * @method $this setInstanceId_20($InstanceId_20)
 * @method string getInstanceId_20()
 * @method $this setLoadBalancerWeight_1($LoadBalancerWeight_1)
 * @method integer getLoadBalancerWeight_1()
 * @method $this setLoadBalancerWeight_2($LoadBalancerWeight_2)
 * @method integer getLoadBalancerWeight_2()
 * @method $this setLoadBalancerWeight_3($LoadBalancerWeight_3)
 * @method integer getLoadBalancerWeight_3()
 * @method $this setLoadBalancerWeight_4($LoadBalancerWeight_4)
 * @method integer getLoadBalancerWeight_4()
 * @method $this setLoadBalancerWeight_5($LoadBalancerWeight_5)
 * @method integer getLoadBalancerWeight_5()
 * @method $this setLoadBalancerWeight_6($LoadBalancerWeight_6)
 * @method integer getLoadBalancerWeight_6()
 * @method $this setLoadBalancerWeight_7($LoadBalancerWeight_7)
 * @method integer getLoadBalancerWeight_7()
 * @method $this setLoadBalancerWeight_8($LoadBalancerWeight_8)
 * @method integer getLoadBalancerWeight_8()
 * @method $this setLoadBalancerWeight_9($LoadBalancerWeight_9)
 * @method integer getLoadBalancerWeight_9()
 * @method $this setLoadBalancerWeight_10($LoadBalancerWeight_10)
 * @method integer getLoadBalancerWeight_10()
 * @method $this setLoadBalancerWeight_11($LoadBalancerWeight_11)
 * @method integer getLoadBalancerWeight_11()
 * @method $this setLoadBalancerWeight_12($LoadBalancerWeight_12)
 * @method integer getLoadBalancerWeight_12()
 * @method $this setLoadBalancerWeight_13($LoadBalancerWeight_13)
 * @method integer getLoadBalancerWeight_13()
 * @method $this setLoadBalancerWeight_14($LoadBalancerWeight_14)
 * @method integer getLoadBalancerWeight_14()
 * @method $this setLoadBalancerWeight_15($LoadBalancerWeight_15)
 * @method integer getLoadBalancerWeight_15()
 * @method $this setLoadBalancerWeight_16($LoadBalancerWeight_16)
 * @method integer getLoadBalancerWeight_16()
 * @method $this setLoadBalancerWeight_17($LoadBalancerWeight_17)
 * @method integer getLoadBalancerWeight_17()
 * @method $this setLoadBalancerWeight_18($LoadBalancerWeight_18)
 * @method integer getLoadBalancerWeight_18()
 * @method $this setLoadBalancerWeight_19($LoadBalancerWeight_19)
 * @method integer getLoadBalancerWeight_19()
 * @method $this setLoadBalancerWeight_20($LoadBalancerWeight_20)
 * @method integer getLoadBalancerWeight_20()
 */
final class AttachInstances extends EssCommon
{
    public $action = 'AttachInstances';
}
