<?php
namespace aliyun\sdk\services\Ess\request;

use aliyun\sdk\services\Ess\EssCommon;

/**
 * @method $this setAccessKeyId($AccessKeyId)
 * @method string getAccessKeyId()
 * @method $this setRegionId($RegionId)
 * @method string getRegionId()
 * @method $this setPageNumber($PageNumber)
 * @method integer getPageNumber()
 * @method $this setPageSize($PageSize)
 * @method integer getPageSize()
 * @method $this setScalingGroupId_1($ScalingGroupId_1)
 * @method string getScalingGroupId_1()
 * @method $this setScalingGroupId_2($ScalingGroupId_2)
 * @method string getScalingGroupId_2()
 * @method $this setScalingGroupId_3($ScalingGroupId_3)
 * @method string getScalingGroupId_3()
 * @method $this setScalingGroupId_4($ScalingGroupId_4)
 * @method string getScalingGroupId_4()
 * @method $this setScalingGroupId_5($ScalingGroupId_5)
 * @method string getScalingGroupId_5()
 * @method $this setScalingGroupId_6($ScalingGroupId_6)
 * @method string getScalingGroupId_6()
 * @method $this setScalingGroupId_7($ScalingGroupId_7)
 * @method string getScalingGroupId_7()
 * @method $this setScalingGroupId_8($ScalingGroupId_8)
 * @method string getScalingGroupId_8()
 * @method $this setScalingGroupId_9($ScalingGroupId_9)
 * @method string getScalingGroupId_9()
 * @method $this setScalingGroupId_10($ScalingGroupId_10)
 * @method string getScalingGroupId_10()
 * @method $this setScalingGroupId_12($ScalingGroupId_12)
 * @method string getScalingGroupId_12()
 * @method $this setScalingGroupId_13($ScalingGroupId_13)
 * @method string getScalingGroupId_13()
 * @method $this setScalingGroupId_14($ScalingGroupId_14)
 * @method string getScalingGroupId_14()
 * @method $this setScalingGroupId_15($ScalingGroupId_15)
 * @method string getScalingGroupId_15()
 * @method $this setScalingGroupId_16($ScalingGroupId_16)
 * @method string getScalingGroupId_16()
 * @method $this setScalingGroupId_17($ScalingGroupId_17)
 * @method string getScalingGroupId_17()
 * @method $this setScalingGroupId_18($ScalingGroupId_18)
 * @method string getScalingGroupId_18()
 * @method $this setScalingGroupId_19($ScalingGroupId_19)
 * @method string getScalingGroupId_19()
 * @method $this setScalingGroupId_20($ScalingGroupId_20)
 * @method string getScalingGroupId_20()
 * @method $this setScalingGroupName($ScalingGroupName)
 * @method string getScalingGroupName()
 * @method $this setScalingGroupName_1($ScalingGroupName_1)
 * @method string getScalingGroupName_1()
 * @method $this setScalingGroupName_2($ScalingGroupName_2)
 * @method string getScalingGroupName_2()
 * @method $this setScalingGroupName_3($ScalingGroupName_3)
 * @method string getScalingGroupName_3()
 * @method $this setScalingGroupName_4($ScalingGroupName_4)
 * @method string getScalingGroupName_4()
 * @method $this setScalingGroupName_5($ScalingGroupName_5)
 * @method string getScalingGroupName_5()
 * @method $this setScalingGroupName_6($ScalingGroupName_6)
 * @method string getScalingGroupName_6()
 * @method $this setScalingGroupName_7($ScalingGroupName_7)
 * @method string getScalingGroupName_7()
 * @method $this setScalingGroupName_8($ScalingGroupName_8)
 * @method string getScalingGroupName_8()
 * @method $this setScalingGroupName_9($ScalingGroupName_9)
 * @method string getScalingGroupName_9()
 * @method $this setScalingGroupName_10($ScalingGroupName_10)
 * @method string getScalingGroupName_10()
 * @method $this setScalingGroupName_11($ScalingGroupName_11)
 * @method string getScalingGroupName_11()
 * @method $this setScalingGroupName_12($ScalingGroupName_12)
 * @method string getScalingGroupName_12()
 * @method $this setScalingGroupName_13($ScalingGroupName_13)
 * @method string getScalingGroupName_13()
 * @method $this setScalingGroupName_14($ScalingGroupName_14)
 * @method string getScalingGroupName_14()
 * @method $this setScalingGroupName_15($ScalingGroupName_15)
 * @method string getScalingGroupName_15()
 * @method $this setScalingGroupName_16($ScalingGroupName_16)
 * @method string getScalingGroupName_16()
 * @method $this setScalingGroupName_17($ScalingGroupName_17)
 * @method string getScalingGroupName_17()
 * @method $this setScalingGroupName_18($ScalingGroupName_18)
 * @method string getScalingGroupName_18()
 * @method $this setScalingGroupName_19($ScalingGroupName_19)
 * @method string getScalingGroupName_19()
 * @method $this setScalingGroupName_20($ScalingGroupName_20)
 * @method string getScalingGroupName_20()
 */
final class DescribeScalingGroups extends EssCommon
{
    public $action = 'DescribeScalingGroups';
}
