<?php
namespace aliyun\sdk\services\DomainIntl\request;

use aliyun\sdk\services\DomainIntl\DomainIntlCommon;

/**
 * @method $this setCountry($Country)
 * @method string getCountry()
 * @method $this setDns2($Dns2)
 * @method string getDns2()
 * @method $this setUserClientIp($UserClientIp)
 * @method string getUserClientIp()
 * @method $this setLang($Lang)
 * @method string getLang()
 * @method $this setDomainName($DomainName)
 * @method string getDomainName()
 * @method $this setSubscriptionDuration($SubscriptionDuration)
 * @method integer getSubscriptionDuration()
 * @method $this setRegistrantProfileId($RegistrantProfileId)
 * @method integer getRegistrantProfileId()
 * @method $this setEnableDomainProxy($EnableDomainProxy)
 * @method boolean getEnableDomainProxy()
 * @method $this setPermitPremiumActivation($PermitPremiumActivation)
 * @method boolean getPermitPremiumActivation()
 * @method $this setAliyunDns($AliyunDns)
 * @method boolean getAliyunDns()
 * @method $this setDns1($Dns1)
 * @method string getDns1()
 * @method $this setCity($City)
 * @method string getCity()
 * @method $this setRegistrantOrganization($RegistrantOrganization)
 * @method string getRegistrantOrganization()
 * @method $this setRegistrantName($RegistrantName)
 * @method string getRegistrantName()
 * @method $this setProvince($Province)
 * @method string getProvince()
 * @method $this setAddress($Address)
 * @method string getAddress()
 * @method $this setEmail($Email)
 * @method string getEmail()
 * @method $this setPostalCode($PostalCode)
 * @method string getPostalCode()
 * @method $this setTelArea($TelArea)
 * @method string getTelArea()
 * @method $this setTelephone($Telephone)
 * @method string getTelephone()
 * @method $this setTelExt($TelExt)
 * @method string getTelExt()
 * @method $this setTrademarkDomainActivation($TrademarkDomainActivation)
 * @method boolean getTrademarkDomainActivation()
 * @method $this setCouponNo($CouponNo)
 * @method string getCouponNo()
 * @method $this setUseCoupon($UseCoupon)
 * @method boolean getUseCoupon()
 * @method $this setPromotionNo($PromotionNo)
 * @method string getPromotionNo()
 * @method $this setUsePromotion($UsePromotion)
 * @method boolean getUsePromotion()
 * @method $this setRegistrantType($RegistrantType)
 * @method string getRegistrantType()
 */
final class SaveSingleTaskForCreatingOrderActivate extends DomainIntlCommon
{
    public $action = 'SaveSingleTaskForCreatingOrderActivate';
}
